### ISSUE TITLE
Severe Server Lag

### ISSUE THREAD

**Issue by xinyuan-liu** [HellFirePvP/AstralSorcery#1047]
I am running a FTB Interactions 1.0.0 server with AstralSorcery 1.10.12 on a high-end computer with 8700K CPU and 16GB RAM.
My server encountered severe lag problem on even early games. I assume this lag is caused by AstralSorcery.
Here are some references for you:

Each time after GameStages saved stages for players, the server will stall for up to 20 seconds:
<img width="1280" alt="屏幕快照 2019-03-29 下午2 04 31" src="https://user-images.githubusercontent.com/17433503/55213208-8df28d00-522d-11e9-8df1-0569c93cd0ed.png">

And the average TPS is healthy:
<img width="1278" alt="屏幕快照 2019-03-29 下午2 20 14" src="https://user-images.githubusercontent.com/17433503/55213328-f0e42400-522d-11e9-88f8-b767487b542b.png">

Here are the profile result from Sampler mod:
![image](https://user-images.githubusercontent.com/17433503/55213418-2d178480-522e-11e9-987b-e50e022929a3.png)
And the complete nps file:
[sampler-snapshot_1.zip](https://github.com/HellFirePvP/AstralSorcery/files/3021418/sampler-snapshot_1.zip)

I assume the doSave method is stalling the server and wonder why this happens.

**Comment by HellFirePvP** [comment]
Inside your world folder (where the folders 'region', 'stats', 'playerdata', and so on) are, there should be a folder called "AstralSorceryData" - would you be so kind as to .zip package it and upload somewhere?
Thanks in advance.

**Comment by xinyuan-liu** [comment]
[AstralSorceryData.zip](https://github.com/HellFirePvP/AstralSorcery/files/3022546/AstralSorceryData.zip)
Here it is.

**Comment by HellFirePvP** [comment]
Will look into approaches to improve performance.

**Comment by SSKirillSS** [comment]
Also encountered a similar problem.
Timings: https://timings.aikar.co/?id=be9e80f79c464e2dada9870e33506177
"Watchdog":
```
Thread: Server thread, state: RUNNABLE
    at java.io.FileOutputStream.write(FileOutputStream.java)
    at java.io.FileOutputStream.write(FileOutputStream.java:290)
    at java.io.DataOutputStream.writeInt(DataOutputStream.java:200)
    at net.minecraft.nbt.NBTTagInt.func_74734_a(SourceFile:25)
    at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474)
    at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35)
    at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:34)
    at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474)
    at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35)
    at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112)
    at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102)
    at net.minecraft.nbt.CompressedStreamTools.func_74795_b(CompressedStreamTools.java:152)
    at hellfirepvp.astralsorcery.common.data.world.WorldCacheManager.saveDataToFile(WorldCacheManager.java:203)
    at hellfirepvp.astralsorcery.common.data.world.WorldCacheManager.doSave(WorldCacheManager.java:230)
    at hellfirepvp.astralsorcery.common.event.listener.EventHandlerIO.onSave(EventHandlerIO.java:58)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1162_EventHandlerIO_onSave_Save.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)
    at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostWorldSaveEvent(SpongeToForgeEventFactory.java:936)
    at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:287)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338)
    at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
    at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465)
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:2472)
    at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:540)
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:3884)
    at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zjn000(MinecraftServer.java:3837)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:687)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Doomgull** [comment]
@SSKirillSS does it happen without Sponge involved?

**Comment by xinyuan-liu** [comment]
I've read the code of `WorldCacheManager` and `RockCrystalBuffer`

**Comment by 123Kappa** [comment]
@Doomgull Yes it does happen without spongeforge. Xinyuan doesnt have spongeforge as you can see in his profiler.

**Comment by Doomgull** [comment]
I asked SSKrillSS because his explicitly had sponge, and wanted to verify if it was same issue or something else.

**Comment by WillThomas** [comment]
A possible workaround for this (if it is making servers unplayable) would be to mount a ramdisk and use that for the folder structure that AS is using.

It goes without saying this could be unstable.

https://docs.observium.org/persistent_ramdisk/

**Comment by xinyuan-liu** [comment]
> A possible workaround for this (if it is making servers unplayable) would be to mount a ramdisk and use that for the folder structure that AS is using.
> 
> It goes without saying this could be unstable.
> 
> https://docs.observium.org/persistent_ramdisk/

Yeah, I use ram disk, but still huge lag. 2.6MB NBT data is too heavy for MC to store. The bottle neck is not the IO but the serialization process on CPU.

**Comment by Doomgull** [comment]
Can you upload that nbt file? 2.6 mb is fucking insane.

**Comment by HellFirePvP** [comment]
As i said above, i'm working on re-organizing data to improve performance.

**Comment by HellFirePvP** [comment]
Moving all data from a per-world storage to chunk capabilities.
Next version will have a command ("/as migrate") which will transfer all rock crystal data to those chunks. Keep in mind that that might be a VERY intensive operation so better do that through console while noone is online!

**Comment by 123Kappa** [comment]
Hello! Thank you so much for fixing the issue. Once you release would us server owners be able to update the mod server-side only? Or clients need to have it too?

**Comment by HellFirePvP** [comment]
I will include other stuff in there aswell, so i'm afraid the clients would also need to update. :/

**Comment by 123Kappa** [comment]
Alright :/ ETA for the update? My players are asking

**Comment by Doomgull** [comment]
ETA is: When it comes out.

If you want immediate notification, join the discord and watch the changelog channel.

**Comment by HellFirePvP** [comment]
Alright, so the update 1.10.13 includes the command /as migrate-data which will convert all the rock crystal data from the "old" per-world format to storing them per chunk making it overall much more performant.

Keep in mind to make backups of your worlds before doing that! Also keep in mind that it might take a while considering you probably have generated a MASSIVE world with tons of chunks and stuff that need to be processed.
Keep me informed about the result if you don't mind.

**Comment by xinyuan-liu** [comment]
Everything goes well now after updating. Thank you a lot for the fixing.

**Comment by HellFirePvP** [comment]
The migration command worked as expected? After some/long time?

**Comment by phit** [comment]
not sure if the migration worked as expected, it was pretty much instant for us on multiple big worlds, but the lag spikes are gone
