### ISSUE TITLE
Weird Client crash when opening guidance computer of a AdvancedRocketry Rocket

### ISSUE THREAD

**Issue by ben-mkiv** [HellFirePvP/AstralSorcery#1049]
no idea why it only happens when opening the guidance computer to me, but theres nothing about advanced rocketry in the stacktrace, so the problem might be related to either thaumcraft or astral.

(rockets are entities in Advanced Rocketry, if that information helps to debug the issue)

```
Description: Unexpected error

java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?
	at hellfirepvp.astralsorcery.common.data.research.ResearchManager.getProgress(ResearchManager.java:86)
	at hellfirepvp.astralsorcery.common.integrations.mods.thaumcraft.perks.key.KeyEnergyShield.on(KeyEnergyShield.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1470_KeyEnergyShield_on_PostProcessVanilla.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at hellfirepvp.astralsorcery.common.event.AttributeEvent.postProcessVanilla(AttributeEvent.java:149)
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111129_g(SourceFile:200)
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111126_e(SourceFile:176)
	at slimeknights.mantle.client.ExtraHeartRenderHandler.renderHealthbar(ExtraHeartRenderHandler.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3269_ExtraHeartRenderHandler_renderHealthbar_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderHealth(GuiIngameForge.java:388)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:154)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by pkmnfrk** [comment]
I can confirm this happens in Enigmatica 2 pack, and is quite frustrating. It's not 100% of the time, though it is quite frequent.

There is some additional information in the log, so here's the contents of my debug.log immediately before the crash:

https://gist.github.com/pkmnfrk/cb0ecb4abb61732d3283f0f83ceab717

**Comment by Doomgull** [comment]
Its because the mod isn't calling the proper player method from forge. #963.

**Comment by pkmnfrk** [comment]
Question: which mod are you implicating? The stack traces don't look very similar, except for the very top. I think it's Cyclic, based on proximity, but I would like to confirm.

Also, what method are they not calling? You reference a conversation with the IC2 people, but never actually say what it is...

**Comment by Doomgull** [comment]
SOME mod is using an improper player class. The issue referenced includes why it happens. Find who is using EntityPlayer, which is improper and breaks Forge convention.

**Comment by ben-mkiv** [comment]
So it looks like that actually one of your server side methods is called on the clientside, why could that happen? Most likely because of some missing client/server side check at some point, or because of broken coremod hooks...

You cant blame other mods if your coremod hooks fail like this
