### ISSUE TITLE
Server crashing at startup

### ISSUE THREAD

**Issue by Remi4001** [HellFirePvP/AstralSorcery#1063]
When I updated astral sorcery in my custom modpack from version 1.10.12 to 1.10.13, the server was crashing during startup and when I came back to version 1.10.12 it was launching correctly.
[crash-2019-04-10_19.36.25-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3066371/crash-2019-04-10_19.36.25-server.txt)
[2019-04-10-4.log.gz](https://github.com/HellFirePvP/AstralSorcery/files/3066377/2019-04-10-4.log.gz)

**Comment by Doomgull** [comment]
Isn't AS crashing.

"java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:34)"

**Comment by Remi4001** [comment]
But is there something I can do to make AS work with the version 1.10.13?

**Comment by Doomgull** [comment]
Open a ticket with the mod throwing the error.

**Comment by KnightMiner** [comment]
This is astral sorcery, read two more into the caused by:
```
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.crafting.Ingredient.field_193371_b from class hellfirepvp.astralsorcery.common.crafting.ItemHandle$HandleIngredient
	at hellfirepvp.astralsorcery.common.crafting.ItemHandle$HandleIngredient.apply(ItemHandle.java:318)
	at net.minecraftforge.common.crafting.CompoundIngredient.apply(CompoundIngredient.java:93)
	at slimeknights.tconstruct.smeltery.TinkerSmeltery.registerRecipeOredictMelting(TinkerSmeltery.java:755)
	at slimeknights.tconstruct.TinkerIntegration.postInit(TinkerIntegration.java:175)
	... 42 more
```
Only reason Tinkers Construct shows up in the report is because the crash happened during one of our initialization methods.

**Comment by HellFirePvP** [comment]
> java.lang.IllegalAccessError

As can be seen on first glance, it's not a implementation problem, this happened on the JVM.
Probably due to an access level change on net.minecraft.item.crafting.Ingredient#matchingStacks - is it private/protected in newer forge versions now?

**Comment by HellFirePvP** [comment]
Temporary fix:
Include crafttweaker in your modpack for the time being.

https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/resources/META-INF/crafttweaker_at.cfg#L11
