### ISSUE TITLE
Player connection fails due to NPE in TickManager.playerTick() / Internal server error

### ISSUE THREAD

**Issue by LemADEC** [HellFirePvP/AstralSorcery#1128]
As of AstralSorcery-1.12.2-1.10.18, after a normal server boot, all players connection failed with the same NPE in TickManager.playerTick():
```
[07:50:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Pixietrixie joined the game
[07:50:20] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@4d793221:
java.lang.NullPointerException: null
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_212]
	at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.playerTick(TickManager.java:91) ~[TickManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1932_TickManager_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:751) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:701) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zka000(NetHandlerPlayServer.java:2556) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
A server restart was required to recover.
Related source code: https://github.com/HellFirePvP/AstralSorcery/blob/c48d47eeeec0c6847b236e4ee702dfc663bcd1ca/src/main/java/hellfirepvp/astralsorcery/common/auxiliary/tick/TickManager.java#L89
Probable cause: TickEvent.Type.PLAYER handler not registered
Modpack: https://minecraft.curseforge.com/projects/spacearchitect/files/2714658

**Comment by LemADEC** [comment]
Related logs: [AstralSorcery1128.zip](https://github.com/HellFirePvP/AstralSorcery/files/3258668/AstralSorcery1128.zip)

**Comment by Doomgull** [comment]
Is this replicable? If so, test under 1.10.19 please.

**Comment by Doomgull** [comment]
@LemADEC replicable under 1.10.20?

**Comment by LemADEC** [comment]
I need an active public server to test it. Since the first occurrence, we've removed AstralSorcery from all our modpacks, so I can't test an update in short term, sorry.
That being said, the code didn't change since 2 months prior to 1.10.18, so I'm not sure what you expect here.

**Comment by LemADEC** [comment]
Information was provided, you denying it doesn't make it disappear

**Comment by Doomgull** [comment]
Being unable to reproduce the issue, having no one else open a report for it, and the original person involved not being able to reproduce because they've removed it entirely means it doesn't matter.

Especially when spongeforge is involved.
