### ISSUE TITLE
Opening my minecraft

### ISSUE THREAD

**Issue by iHarvL** [HellFirePvP/AstralSorcery#1130]
Every time I try and open my minecraft (on version 1.12.2) it always puts up this message

   "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)"

I've tried reopening my minecraft, and it didn't work, tried re-downloading the mod, but it always comes up with the same message.

What do I do?

**Comment by iHarvL** [comment]
Full crash message:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.10.19 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/9/19 1:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.BufferBuilder.<init>(BufferBuilder.java:78)
	at hellfirepvp.astralsorcery.client.util.BufferBatch.<init>(BufferBatch.java:27)
	at hellfirepvp.astralsorcery.client.util.BufferBatch.make(BufferBatch.java:32)
	at hellfirepvp.astralsorcery.client.gui.perk.BatchPerkContext.addContext(BatchPerkContext.java:43)
	at hellfirepvp.astralsorcery.client.gui.perk.PerkRenderGroup.batchRegister(PerkRenderGroup.java:49)
	at hellfirepvp.astralsorcery.client.gui.GuiJournalPerkTree.initializeDrawBuffer(GuiJournalPerkTree.java:163)
	at hellfirepvp.astralsorcery.client.ClientProxy.init(ClientProxy.java:186)
	at hellfirepvp.astralsorcery.AstralSorcery.init(AstralSorcery.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 180330072 bytes (171 MB) / 637534208 bytes (608 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version                  | Source                                        | Signature                                |
	|:----- |:---------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft              | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHI  | mcp                    | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHI  | FML                    | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                  | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | baubles                | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHE  | astralsorcery          | 1.10.19                  | astralsorcery-1.12.2-1.10.19 (1).jar          | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | gravestone             | 1.10.2                   | gravestone-1.10.2.jar                         | None                                     |
	| LCH   | guideapi               | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
	| LCH   | waila                  | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCH   | inventorytweaks        | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | jei                    | 4.15.0.277               | jei_1.12.2-4.15.0.277.jar                     | None                                     |
	| LCH   | journeymap             | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| LCH   | vampirism              | 1.5.0-beta.3             | Vampirism-1.12.2-1.5.0-beta.3.jar             | None                                     |
	| LCH   | teamlapen-lib          | 1.5.0-beta.3             | Vampirism-1.12.2-1.5.0-beta.3.jar             | None                                     |
	| LCH   | vampirism_integrations | vampirism_integrations   | VampirismIntegrations-1.12.2-1.1.0-beta.1.jar | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.10.19 (1).jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2057' Renderer: 'Mobile Intel(R) 4 Series Express Chipset Family'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2057
	OpenGlRenderer: Mobile Intel(R) 4 Series Express Chipset Family
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by Doomgull** [comment]
You ran out of memory. Not AS.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)
Caused by: java.lang.OutOfMemoryError

**Comment by iHarvL** [comment]
I tried deleting some extra mods i wouldn't use and that didnt fix the problem. The same error message just appeared.

**Comment by Doomgull** [comment]
You. Ran. Out. Of. Memory. It says it very clearly in that crash log.

You need to allocate more than 1 gb of memory, which it also lists in the crash log.
