### ISSUE TITLE
Error in packet preventing me from logging on to server (most likely)

### ISSUE THREAD

**Issue by SwissCheese5** [HellFirePvP/AstralSorcery#1136]
```[15:56:41]` [Server thread/ERROR] [FML]: A TileEntity type hellfirepvp.astralsorcery.common.tile.network.TileCrystalPrismLens has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
	at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:228) ~[TileCrystalLens.class:?]
	at hellfirepvp.astralsorcery.common.tile.base.TileEntitySynchronized.func_189515_b(TileEntitySynchronized.java:47) ~[TileEntitySynchronized.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:382) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]```

**Comment by Doomgull** [comment]
The lens has bad State data, probably because of bad stats. If you obtained it be a special mod pack method, not the default method, please delete it and do not use that method again
