### ISSUE TITLE
The game crashed whilst ticking player

### ISSUE THREAD

**Issue by Nightelf23** [HellFirePvP/AstralSorcery#1182]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 9/10/19 4:41 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.minecolonies.coremod.items.ItemAncientTome.func_77663_a(ItemAncientTome.java:43)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.items.ItemAncientTome.func_77663_a(ItemAncientTome.java:43)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 368
	Entity Name: NightElf23
	Entity's Exact location: 162.50, 70.00, 261.50
	Entity's Block location: World: (162,70,261), Chunk: (at 2,4,5 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4d68eeee
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 751053440 bytes (716 MB) / 1677721600 bytes (1600 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2795 Optifine OptiFine_1.12.2_HD_U_E3 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version               | Source                                           | Signature                                |
	|:------ |:-------------------- |:--------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42                  | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2795.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2795          | forge-1.12.2-14.23.5.2795.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | baubles              | 1.5.2                 | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | astralsorcery        | 1.10.20               | astralsorcery-1.12.2-1.10.20.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | biomesoplenty        | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
	| LCHIJA | cucumber             | 1.1.3                 | Cucumber-1.12.2-1.1.3.jar                        | None                                     |
	| LCHIJA | cfm                  | 4.1.5                 | MrCrayfishs-Furniture-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | mysticalagriculture  | 1.7.5                 | MysticalAgriculture-1.12.2-1.7.5.jar             | None                                     |
	| LCHIJA | radixcore            | 1.12.x-2.2.1          | RadixCore-1.12.x-2.2.1-universal.jar             | None                                     |
	| LCHIJA | additionalstructures | 2.2.3                 | Rex'

**Comment by Doomgull** [comment]
Astral Sorcery isnt in the crash report nor the stack trace.

Talk to minecolonies.
