### ISSUE TITLE
ClientCameraManager and Modular Powersuits Crashing

### ISSUE THREAD

**Issue by NicolasNewman** [HellFirePvP/AstralSorcery#1198]
When I attempted to use the Attunement Alter, my camera switched to a top down perspective and the game proceed to freeze and CTD. Upon looking at the logs, I found the following error:

```
java.lang.ClassCastException: hellfirepvp.astralsorcery.client.util.camera.ClientCameraManager$EntityClientReplacement cannot be cast to net.minecraft.client.entity.EntityPlayerSP
```
Proceded by the following four invocations:
```
at net.machinemuse.powersuits.control.PlayerMovementInputWrapper.fromClient(PlayerMovementInputWrapper.java:66)
at net.machinemuse.powersuits.control.PlayerMovementInputWrapper.get(PlayerMovementInputWrapper.java:35)
at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickActive(JetPackModule.java:50)
at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.java:72)
```

Luckily a simple fix is to remove the armor before attuning

[Full crash report](https://github.com/HellFirePvP/AstralSorcery/files/3774097/crash-log.txt)

**Comment by Doomgull** [comment]
Address with powersuits.
