### ISSUE TITLE
Clicking constellation in journal causes crash

### ISSUE THREAD

**Issue by CDArena** [HellFirePvP/AstralSorcery#131]
Problem: Opened journal after collecting a few constellations; clicking on one of the constellations in the journal crashed the game

VERSION:
AstralCore (astralsorcery-1.3.2-beta.jar)
bug found in FTB Illumination mod pack (v 0.8.0)

CRASH LOG DETAIL:
PM
Description: Updating screen events
java.lang.NullPointerException: Updating screen events at  hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.buildLines(GuiJournalConstellationDetails.java:79) 
at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.<init>(GuiJournalConstellationDetails.java:69) 
at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster.func_73864_a(GuiJournalConstellationCluster.java:274) 
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.buildLines(GuiJournalConstellationDetails.java:79)
at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.<init>(GuiJournalConstellationDetails.java:69)
at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster.func_73864_a(GuiJournalConstellationCluster.java:274)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
-- Affected screen --
Details:
Screen name: hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster
-- Affected level --
Details:
Level name: MpServer
All players: 1 total

**Comment by Electrofried** [comment]
[crash-2017-04-23_10.14.03-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/949511/crash-2017-04-23_10.14.03-client.txt)


Another report from a different user having the same issue.

**Comment by HellFirePvP** [comment]
#127
