### ISSUE TITLE
Crash on Startup, ExU2 and Astral Sorcery Suspected

### ISSUE THREAD

**Issue by puncrafter** [HellFirePvP/AstralSorcery#1401]
AS Version: astralsorcery-1.12.2-1.10.27
ExU2 Version: extrautils2-1.12-1.9.9

Full Crash Report Here: [https://pastebin.com/ePUabZDd](https://pastebin.com/ePUabZDd)

When the game crashes, the game is at 5/7 Initalizing Mods Phase 3, PostInitalizing Astral Sorcery, and it is loading the ItemColorizationHelper resource.

Removing either of the two mods fixes it, but both mods are integral to the modpack I'm making.

**Comment by Doomgull** [comment]
Exu2:

Caused by: java.lang.NullPointerException
    at com.rwtema.extrautils2.items.ItemIngredients.getType(ItemIngredients.java:136)
    at com.rwtema.extrautils2.items.ItemIngredients.getTexture(ItemIngredients.java:123)
    at
