### ISSUE TITLE
Unexpected crash - ticking entity

### ISSUE THREAD

**Issue by piesio98** [HellFirePvP/AstralSorcery#1413]
It is crashing randomly. 

logs: 
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/5364561/latest.log)

crash log:
[crash-2020-10-12_12.22.31-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5364562/crash-2020-10-12_12.22.31-server.txt)

**Comment by Doomgull** [comment]
This has nothing to do with Astral Sorcery. A salmon is having issues pathfinding code in the stack trace:
Stacktrace:
	at net.minecraft.pathfinding.SwimNodeProcessor.func_176159_a(SourceFile:86)
	at net.minecraft.pathfinding.SwimNodeProcessor.func_186328_b(SourceFile:70)
	at net.minecraft.pathfinding.SwimNodeProcessor.func_222859_a(SourceFile:36)
	at net.minecraft.pathfinding.PathFinder.func_227479_a_(SourceFile:619)
	at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:559)
	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:607)
	at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:102)
	at net.minecraft.pathfinding.PathNavigator.func_225466_a(PathNavigator.java:92)
	at net.minecraft.entity.ai.goal.AvoidEntityGoal.func_75250_a(SourceFile:67)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22)
	at com.performant.coremod.entity.ai.goals.CustomPriotizedSlowedGoal.func_75250_a(CustomPriotizedSlowedGoal.java:52)
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:355)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1310)
	at net.minecraft.entity.passive.fish.AbstractFishEntity.func_70636_d(SourceFile:149)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.entity.passive.fish.AbstractGroupFishEntity.func_70071_h_(SourceFile:75)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
