### ISSUE TITLE
cascading worldgen caused by AstralS put my server down

### ISSUE THREAD

**Issue by fulc927** [HellFirePvP/AstralSorcery#154]
Using a fresh **astralsorcery-1.3.2-beta**, after playing nearly 1 hour and half on **1.11.2** i get a server crash:

server side i have :
**forge-1.11.2-13.20.0.2285
jdk-8u102-linux-x64.rpm**

Ready to give more accurate informations to get this solved.

[19:09:55] [Server thread/WARN] [FML]: Astral Sorcery loaded a new chunk (0, -19  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:10:16] [Server thread/WARN] [FML]: Astral Sorcery loaded a new chunk (1, -23  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:10:16] [Server thread/WARN] [FML]: Astral Sorcery loaded a new chunk (1, -24  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:10:17] [Server thread/WARN] [FML]: Astral Sorcery loaded a new chunk (3, -27  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:10:50] [Server Watchdog/FATAL]: A single server tick took 60,00 seconds (should be max 0,05)
[19:10:50] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
[19:10:51] [Server Watchdog/ERROR]: This crash report has been saved to: /home/mcserver/minecraft2/./crash-reports/crash-2017-05-02_19.10.51-server.txt

**Comment by HellFirePvP** [comment]
1) The actual crash report please. This doesn't help.
2) See #151

**Comment by fulc927** [comment]
**please find  crash-2017-05-02_19.10.51-server.txt attached**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.3.2-beta.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 02/05/17 19:10
Description: Watching Server

java.lang.Error
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:394)
        at net.minecraft.world.gen.ChunkProviderServer.func_73149_a(ChunkProviderServer.java:318)
        at net.minecraft.world.WorldServer.func_175680_a(WorldServer.java:348)
        at net.minecraft.world.World.func_175663_a(World.java:279)
        at net.minecraft.world.World.func_175648_a(World.java:243)
        at net.minecraft.world.World.func_180500_c(World.java:2802)
        at net.minecraft.world.World.func_175664_x(World.java:2738)
        at net.minecraft.world.chunk.Chunk.func_150811_f(Chunk.java:1381)
        at net.minecraft.world.chunk.Chunk.func_150809_p(Chunk.java:1289)
        at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1054)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:397)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:394)
        at net.minecraft.world.gen.ChunkProviderServer.func_73149_a(ChunkProviderServer.java:318)
        at net.minecraft.world.WorldServer.func_175680_a(WorldServer.java:348)
        at net.minecraft.world.World.func_175663_a(World.java:279)
        at net.minecraft.world.World.func_175648_a(World.java:243)
        at net.minecraft.world.World.func_180500_c(World.java:2802)
        at net.minecraft.world.World.func_175664_x(World.java:2738)
        at net.minecraft.world.chunk.Chunk.func_150811_f(Chunk.java:1381)
        at net.minecraft.world.chunk.Chunk.func_150809_p(Chunk.java:1289)
        at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1054)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:397)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)

-- Thread Dump --
Details:
        Threads: "process reaper" Id=148 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@6f116c48
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@6f116c48
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...


"Netty Epoll Server IO #6" Id=33 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #5" Id=32 RUNNABLE
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #4" Id=31 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #3" Id=30 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #2" Id=29 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"File IO Thread" Id=46 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
        at java.lang.Thread.run(Thread.java:745)


"Chunk I/O Executor Thread-1" Id=45 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@61d68fda
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@61d68fda
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #1" Id=28 RUNNABLE
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"Server Watchdog" Id=37 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
        at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:46)
        at java.lang.Thread.run(Thread.java:745)


"Netty Epoll Server IO #0" Id=27 RUNNABLE
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)


"Timer-0" Id=26 TIMED_WAITING on java.util.TaskQueue@65e90738
        at java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@65e90738
        at java.util.TimerThread.mainLoop(Timer.java:552)
        at java.util.TimerThread.run(Timer.java:505)


"Server console handler" Id=20 RUNNABLE (in native)
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
        -  locked jline.internal.NonBlockingInputStream@20eb85e1
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
        -  locked jline.internal.NonBlockingInputStream@20eb85e1
        at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
        -  locked jline.internal.NonBlockingInputStream@20eb85e1
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136)
        ...


"DestroyJavaVM" Id=19 RUNNABLE


"Server thread" Id=17 RUNNABLE
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:394)
        at net.minecraft.world.gen.ChunkProviderServer.func_73149_a(ChunkProviderServer.java:318)
        at net.minecraft.world.WorldServer.func_175680_a(WorldServer.java:348)
        at net.minecraft.world.World.func_175663_a(World.java:279)
        at net.minecraft.world.World.func_175648_a(World.java:243)
        at net.minecraft.world.World.func_180500_c(World.java:2802)
        at net.minecraft.world.World.func_175664_x(World.java:2738)
        at net.minecraft.world.chunk.Chunk.func_150811_f(Chunk.java:1381)
        ...


"Server Infinisleeper" Id=16 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:78)


"Snooper Timer" Id=15 TIMED_WAITING on java.util.TaskQueue@44fcde98
        at java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@44fcde98
        at java.util.TimerThread.mainLoop(Timer.java:552)
        at java.util.TimerThread.run(Timer.java:505)


"NonBlockingInputStreamThread" Id=13 WAITING on jline.internal.NonBlockingInputStream@20eb85e1 owned by "Server console handler" Id=20
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@20eb85e1
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
        at java.lang.Thread.run(Thread.java:745)


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@11812182
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@11812182
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@3c7c244d
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@3c7c244d
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)



Stacktrace:
        at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:63)
        at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
        Minecraft Version: 1.11.2
        Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
        Java Version: 1.8.0_102, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3649455240 bytes (3480 MB) / 4167041024 bytes (3974 MB) up to 4167041024 bytes (3974 MB)
        JVM Flags: 2 total; -Xmx3999M -Xms3999M
        IntCache: cache: 5, tcache: 1, allocated: 12, tallocated: 94
        FML: MCP 9.38 Powered by Forge 13.20.0.2285 8 mods loaded, 8 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       minecraft{1.11.2} [Minecraft] (minecraft.jar)
        UCHIJAAAA       mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2285-universal.jar)
        UCHIJAAAA       forge{13.20.0.2285} [Minecraft Forge] (forge-1.11.2-13.20.0.2285-universal.jar)
        UCHIJAAAA       astralsorcery{1.3.2-beta} [Astral Sorcery] (astralsorcery-1.3.2-beta.jar)
        UCHIJAAAA       mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar)
        UCHIJAAAA       mycommands{1.11.2-01} [MY Commands] (mycommand.zip)
        UCHIJAAAA       refinedstorage{1.4.2} [Refined Storage] (refinedstorage-1.4.2.jar)
        Loaded coremods (and transformers):
AstralCore (astralsorcery-1.3.2-beta.jar)

        Profiler Position: N/A (disabled)
        Player Count: 1 / 2; [EntityPlayerMP['fulcrap'/10679, l='world', x=182,34, y=67,00, z=-300,30]]
        Is Modded: Definitely; Server brand changed

**Comment by fulc927** [comment]
**please find crash report attached**

[crash-2017-05-02_19.10.51-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/971408/crash-2017-05-02_19.10.51-server.txt)

**Comment by HellFirePvP** [comment]
http://i.imgur.com/1AskLox.png

Whatever this is, it's someone messing with chunk generation it seems? The only place where i've seen this before was back when i was writing spigot/bukkit plugins and forcibly manipulated the chunks that got sent to the client. I'm doing nothing that comes even remotely close to this in AS.

In case this is caused by some shenanigans due to the cascading chunk gen, that's been adressed for the next version. In case this is not caused by the recursive chunk gen, i can't do anything about it.

**Comment by HellFirePvP** [comment]
Well, not much more to say to that. either it's gonna be adressed with that as of next version, or it's not really something i can influence.
