### ISSUE TITLE
Progression load issue on valhelsia server

### ISSUE THREAD

**Issue by Ko3ntjuh** [HellFirePvP/AstralSorcery#1574]
After upgrading our Valhelsia 3 server, the below error occurred when logging in again.  I got the message ingame;

![image](https://user-images.githubusercontent.com/76263474/102697490-5c59fa80-4236-11eb-8200-78a2ac963d7b.png)

Attached also the two error files mentioned being generated. 

[67eb7aac-539b-4c27-90e8-90bd0c7f0035.astral.zip](https://github.com/HellFirePvP/AstralSorcery/files/5720017/67eb7aac-539b-4c27-90e8-90bd0c7f0035.astral.zip)

[19Dec2020 19:59:24.079] [Server thread/INFO] [Waila/]: Syncing config to ko3ntjuh (67eb7aac-539b-4c27-90e8-90bd0c7f0035)
[19Dec2020 19:59:24.089] [Server thread/WARN] [Astral Sorcery/]: Unable to load progress from default progress file. Attempting loading backup.
[19Dec2020 19:59:24.089] [Server thread/WARN] [Astral Sorcery/]: Erroneous file: 67eb7aac-539b-4c27-90e8-90bd0c7f0035.astral
[19Dec2020 19:59:24.089] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: astralsorcery:connector-tk-astralsorcery:evorsio_connector_2
[19Dec2020 19:59:24.090] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33)
[19Dec2020 19:59:24.090] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42)
[19Dec2020 19:59:24.090] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.AstralSorcery.key(AstralSorcery.java:63)
[19Dec2020 19:59:24.090] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.PlayerPerkData.loadLegacyData(PlayerPerkData.java:390)
[19Dec2020 19:59:24.091] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.PlayerPerkData.load(PlayerPerkData.java:256)
[19Dec2020 19:59:24.091] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.PlayerProgress.load(PlayerProgress.java:101)
[19Dec2020 19:59:24.091] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.load_unsafeFromNBT(ResearchHelper.java:154)
[19Dec2020 19:59:24.091] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.load_unsafe(ResearchHelper.java:148)
[19Dec2020 19:59:24.092] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.loadPlayerKnowledge(ResearchHelper.java:108)
[19Dec2020 19:59:24.092] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.getProgress(ResearchHelper.java:82)
[19Dec2020 19:59:24.092] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.getProgressServer(ResearchHelper.java:75)
[19Dec2020 19:59:24.092] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.getProgress(ResearchHelper.java:59)
[19Dec2020 19:59:24.093] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache.onPlayerConnect(EventHandlerCache.java:120)
[19Dec2020 19:59:24.093] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraftforge.eventbus.ASMEventHandler_42_EventHandlerCache_onPlayerConnect_PlayerLoggedInEvent.invoke(.dynamic)
[19Dec2020 19:59:24.093] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[19Dec2020 19:59:24.093] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[19Dec2020 19:59:24.094] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
[19Dec2020 19:59:24.094] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
[19Dec2020 19:59:24.095] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
[19Dec2020 19:59:24.095] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
[19Dec2020 19:59:24.095] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
[19Dec2020 19:59:24.096] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
[19Dec2020 19:59:24.096] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
[19Dec2020 19:59:24.096] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[19Dec2020 19:59:24.096] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
[19Dec2020 19:59:24.096] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
[19Dec2020 19:59:24.097] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
[19Dec2020 19:59:24.097] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:112]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[19Dec2020 19:59:24.102] [Server thread/WARN] [Astral Sorcery/]: Unable to load progress from backup progress file. Copying relevant files to error files.
[19Dec2020 19:59:24.102] [Server thread/WARN] [Astral Sorcery/]: Erroneous file: 67eb7aac-539b-4c27-90e8-90bd0c7f0035.astralback
[19Dec2020 19:59:24.103] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: astralsorcery:connector-tk-astralsorcery:evorsio_connector_2
[19Dec2020 19:59:24.103] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33)
[19Dec2020 19:59:24.103] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42)
[19Dec2020 19:59:24.103] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.AstralSorcery.key(AstralSorcery.java:63)
[19Dec2020 19:59:24.104] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.PlayerPerkData.loadLegacyData(PlayerPerkData.java:390)
[19Dec2020 19:59:24.104] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.PlayerPerkData.load(PlayerPerkData.java:256)
[19Dec2020 19:59:24.104] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.PlayerProgress.load(PlayerProgress.java:101)
[19Dec2020 19:59:24.104] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.load_unsafeFromNBT(ResearchHelper.java:154)
[19Dec2020 19:59:24.104] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.load_unsafe(ResearchHelper.java:148)
[19Dec2020 19:59:24.105] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.loadPlayerKnowledge(ResearchHelper.java:116)
[19Dec2020 19:59:24.105] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.getProgress(ResearchHelper.java:82)
[19Dec2020 19:59:24.105] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.getProgressServer(ResearchHelper.java:75)
[19Dec2020 19:59:24.105] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.data.research.ResearchHelper.getProgress(ResearchHelper.java:59)
[19Dec2020 19:59:24.106] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache.onPlayerConnect(EventHandlerCache.java:120)
[19Dec2020 19:59:24.106] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraftforge.eventbus.ASMEventHandler_42_EventHandlerCache_onPlayerConnect_PlayerLoggedInEvent.invoke(.dynamic)
[19Dec2020 19:59:24.106] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[19Dec2020 19:59:24.106] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[19Dec2020 19:59:24.106] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
[19Dec2020 19:59:24.107] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
[19Dec2020 19:59:24.107] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
[19Dec2020 19:59:24.107] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
[19Dec2020 19:59:24.107] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
[19Dec2020 19:59:24.107] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
[19Dec2020 19:59:24.109] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
[19Dec2020 19:59:24.109] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[19Dec2020 19:59:24.110] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
[19Dec2020 19:59:24.110] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
[19Dec2020 19:59:24.110] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
[19Dec2020 19:59:24.110] [Server thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.data.research.ResearchHelper:loadPlayerKnowledge:121]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[19Dec2020 19:59:24.111] [Server thread/WARN] [Astral Sorcery/]: Copied progression files to error files. In case you would like to try me (HellFirePvP) to maybe see what i can do about maybe recovering the files,
[19Dec2020 19:59:24.112] [Server thread/WARN] [Astral Sorcery/]: send them over to me at the issue tracker https://github.com/HellFirePvP/AstralSorcery/issues - 90% that i won't be able to do anything, but reporting it would still be great.

**Comment by PocketfulOfGeese** [comment]
What Astral Sorcery versions were involved pre-update and post-update?

**Comment by Ko3ntjuh** [comment]
Pre update version: Astral Sorcery 1.16.4-1.13.1
Post update version: Astral Sorcery 1.16.4-1.13.6

**Comment by superbrias** [comment]
I think the issue wasn't fixed in 1.13.7 or I have a similar yet different issue. Should I post my error log and .astral files or... (should I do it in a pastebin if so?)

unless the update doesn't fix data loading from previous versions...

**Comment by PocketfulOfGeese** [comment]
pastebin it up

**Comment by HellFirePvP** [comment]
Unnecessary, most likely the exact same issue since it's a change in data format from 1.13.1 to newer versions i didn't expect.

Guess that's what happens when packs never update and issues that should've happened in 1.13.2 happen in 1.13.6 :P

**Comment by HellFirePvP** [comment]
Test again with https://jenkins.hellfiredev.net/job/AstralSorcery/job/1.16-indev/55/artifact/astralsorcery-1.16.4-1.13.8.jar

**Comment by superbrias** [comment]
that got it working, want anything else from me?
