### ISSUE TITLE
Shooting Star Crash 1.12.2

### ISSUE THREAD

**Issue by Mars455** [HellFirePvP/AstralSorcery#1631]
Happens every so often, 1.12.2 version 1.10.27

Time: 2021-01-07 15:54:39 GMT
Description: Ticking entity

java.lang.ClassCastException: java.lang.Long cannot be cast to hellfirepvp.astralsorcery.common.util.data.Vector3
    at hellfirepvp.astralsorcery.common.entities.EntityShootingStar.correctMovement(EntityShootingStar.java:88)
    at hellfirepvp.astralsorcery.common.entities.EntityShootingStar.onUpdate(EntityShootingStar.java:125)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zbe000$updateEntity(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by PocketfulOfGeese** [comment]
What other mods are involved, forge version, etc?
