### ISSUE TITLE
Crash after open workbench 1.12.2

### ISSUE THREAD

**Issue by Exzept1on** [HellFirePvP/AstralSorcery#1633]
When I open any of the workbenches I get this error in the minecraft console.
Version 1.12.2
Forge Version Latest
Mod Version Latest

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2021-01-09 20:24:28 NOVT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field net.minecraft.inventory.ContainerWorkbench.field_178145_h from class hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.inventory.ContainerWorkbench.field_178145_h from class hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer
    at hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer.onContainerOpen(EventHandlerServer.java:156)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1259_EventHandlerServer_onContainerOpen_Open.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:102)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at shadows.fastbench.block.BlockFastBench.onBlockActivated(BlockFastBench.java:26)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

**Comment by PocketfulOfGeese** [comment]
Mod interaction. check your list for something changing tables. Also, "Latest" is never an appropriate version number.
