### ISSUE TITLE
Crashes on use of transportation wand

### ISSUE THREAD

**Issue by GlacialSkyfarer** [HellFirePvP/AstralSorcery#1696]
When I try to use transportation wand it crashes the game with error code 0

**Comment by GlacialSkyfarer** [comment]
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/5937777/latest.log)

**Comment by PocketfulOfGeese** [comment]
Something in the world is unhappy, doesn't look like anything to do with the wand itself. Where are you going and does it happen every time, even if tried elsewhere in the world?

"[06Feb2021 15:06:09.312] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception while ticking
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$12343/6168220.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.loot.conditions.EntityHasProperty.test(SourceFile:38) ~[?:?]
	at net.minecraft.loot.conditions.EntityHasProperty.test(SourceFile:17) ~[?:?]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?]"

**Comment by GlacialSkyfarer** [comment]
Hmm ok I'll try killing everything but players

**Comment by GlacialSkyfarer** [comment]
The thing is, it always happens if I use the wand and only when I use the wand

**Comment by PocketfulOfGeese** [comment]
AS still isnt in the trace. Vanilla is having a bad time.
