### ISSUE TITLE
Catching manual debug crash

### ISSUE THREAD

**Issue by Techjar** [HellFirePvP/AstralSorcery#174]
I cannot trigger a manual debug crash, as your mod is catching the exception somehow. Here's the stack trace. It spews this constantly and breaks keyboard input.

```
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: java.lang.reflect.InvocationTargetException
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent.fireKeyboardEvent(ClientKeyboardInputEvent.java:36)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1999)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1247)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:452)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:06:14] [Client thread/INFO] [STDERR/]: [hellfirepvp.astralsorcery.common.event.ClientKeyboardInputEvent:fireKeyboardEvent:38]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:06:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: Caused by: net.minecraft.util.ReportedException: Manually triggered debug crash
[13:06:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2122)
[13:06:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 19 more
[13:06:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.Throwable
[13:06:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 20 more
```

**Comment by HellFirePvP** [comment]
This has been specifically worked around in version 1.4.0

**Comment by HellFirePvP** [comment]
On that note, 1.4.0 breaks other stuff for the exact same reason, so that'll be fixed on tuesday when i make the next mod update.

**Comment by Techjar** [comment]
Ah ok, thanks for the quick response. Glad to know this is fixed already, I'll get that update when it comes out.
