### ISSUE TITLE
There was a critical exception handling a packet on channel Astral Sorcery

### ISSUE THREAD

**Issue by 3269199948** [HellFirePvP/AstralSorcery#1740]
game version: 1.12.2
astralsorcery-1.12.2-1.10.27.jar

[18:54:30] [Netty Epoll Server IO #3/ERROR]: There was a critical exception handling a packet on channel Astral Sorcery
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
        at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
        at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
        at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:git-CatServer-1.12.2-f2bc11f]
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-f2bc11f]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:git-CatServer-1.12.2-f2bc11f]
        at hellfirepvp.astralsorcery.common.data.SyncDataHolder.syncAllDataTo(SyncDataHolder.java:97) ~[SyncDataHolder.class:?]
        at hellfirepvp.astralsorcery.common.event.listener.EventHandlerNetwork.lambda$onLogin$0(EventHandlerNetwork.java:41) ~[EventHandlerNetwork.class:?]
        at hellfirepvp.astralsorcery.common.CommonScheduler.tick(CommonScheduler.java:45) ~[CommonScheduler.class:?]
        at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.serverTick(TickManager.java:63) ~[TickManager.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1267_TickManager_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-f2bc11f]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-f2bc11f]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268) ~[FMLCommonHandler.class:git-CatServer-1.12.2-f2bc11f]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:819) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[18:54:30] [Netty Epoll Server IO #3/ERROR]: Network Disconnect: A fatal error has occurred, this connection is terminated
[18:54:30] [Server thread/INFO]: ICARUS lost connection: A fatal error has occurred, this connection is terminated

**Comment by HellFirePvP** [comment]
Outdated. Won't fix, also not supporting non-forge environments.
