### ISSUE TITLE
Mod causing crash on initialization

### ISSUE THREAD

**Issue by McSquizzleswag** [HellFirePvP/AstralSorcery#1912]
Your mod, along with Reliquary and Simple Storage Network are causing a crash, I am telling the devs of the other mods of this issue too. My pack has the latest version of your mod
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/7699242/latest.log)

**Comment by PocketfulOfGeese** [comment]
AS isnt even in that trace until entirely too many other mods touch it. Looks like reliquary is the issue, not SSN or AS.

Issue lies here:
java.lang.NullPointerException: Initializing game
	at xreliquary.items.VoidTearItem$1.getCapability(VoidTearItem.java:90) ~[?:1.16.5-1.3.5.1100] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:102) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:174) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM}
