### ISSUE TITLE
Delete this issue report

### ISSUE THREAD

**Issue by McSquizzleswag** [HellFirePvP/AstralSorcery#1925]
AS isnt even in that trace until entirely too many other mods touch it. Looks like reliquary is the issue, not SSN or AS.

Issue lies here:
java.lang.NullPointerException: Initializing game
	at xreliquary.items.VoidTearItem$1.getCapability(VoidTearItem.java:90) ~[?:1.16.5-1.3.5.1100] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:102) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:174) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM}

_Originally posted by @Doomgull in https://github.com/HellFirePvP/AstralSorcery/issues/1912#issuecomment-991944873_

**Comment by McSquizzleswag** [comment]
Can you just delete this, I'm trying to get it to the dev of Reliquary
