### ISSUE TITLE
Crash when attuning player [Evorsio]

### ISSUE THREAD

**Issue by I3estOFF** [HellFirePvP/AstralSorcery#1939]
Game crashed, after jumping on Attunement Altar, i can't join my world :( game is crashing please help
Minecraft 1.16.5
Crash log
https://gist.github.com/I3estOFF/40172214ec5b846d54c6517ab056819c
Latest log
https://gist.github.com/I3estOFF/3031fa40fc4e9b13293b7029bb70cd4e
Crash after reopening the world
https://gist.github.com/I3estOFF/e6cd7013886509bd915449fce6755da6

![image](https://user-images.githubusercontent.com/63112899/159699679-a932146d-f1a4-4397-9c9a-219b832ab964.png)

**Comment by PocketfulOfGeese** [comment]
#1594 

Issue in Traveler's Index

java.lang.NullPointerException: Saving entity NBT
	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:32) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:16) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:29) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:14) ~[?:1.16.4-1.0.2] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:127) ~[?:?] {re:classloading}
