### ISSUE TITLE
Tick lasts infinite time after loading world. Issue arises after the first time the server is restarted.

### ISSUE THREAD

**Issue by ZiphonOfficial** [HellFirePvP/AstralSorcery#1949]
java.lang.Error: ServerHangWatchdog detected that a single server tick took 90.00 seconds (should be max 0.05)
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_223705_bi(SourceFile:139) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:129) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217353_a(World.java:167) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_212866_a_(World.java:163) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_175726_f(World.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_175625_s(World.java:598) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:88) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.fluid.FluidNetwork.scanGraph(FluidNetwork.java:39) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.NetworkManager.formNetworkAt(NetworkManager.java:76) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.NetworkManager.addPipe(NetworkManager.java:132) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.tile.PipeTileEntity.func_145829_t(PipeTileEntity.java:53) ~[refinedpipes:0.5.2] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:409) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:399) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:402) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betternether.mixins.json:ChunkSerializerMixin,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:APP:ferritecore.chunknbt.mixin.json:ChunkSerializerMixin,pl:mixin:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer.md39ea81$lambda$replacePostLoad$0$0(ChunkSerializer.java:1582) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betternether.mixins.json:ChunkSerializerMixin,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:APP:ferritecore.chunknbt.mixin.json:ChunkSerializerMixin,pl:mixin:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer$$Lambda$27964/0x0000000844579440.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:457) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.func_219237_a_(ChunkManager.java:582) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$28126/0x00000008445bb440.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$$Lambda$28048/0x000000084459f040.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:569) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$28123/0x00000008445ba840.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$27919/0x000000084456d040.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:519) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:527) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217353_a(World.java:167) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_212866_a_(World.java:163) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_175726_f(World.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_175625_s(World.java:598) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:88) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.scanGraph(Network.java:36) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.energy.EnergyNetwork.scanGraph(EnergyNetwork.java:32) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.Network.update(Network.java:54) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.network.energy.EnergyNetwork.update(EnergyNetwork.java:55) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.setup.CommonSetup.lambda$onWorldTick$13(CommonSetup.java:151) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.setup.CommonSetup$$Lambda$28640/0x0000000844697840.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap$Values.forEach(HashMap.java:977) ~[?:?] {}
	at com.refinedmods.refinedpipes.setup.CommonSetup.onWorldTick(CommonSetup.java:151) ~[refinedpipes:0.5.2] {re:classloading}
	at com.refinedmods.refinedpipes.RefinedPipes$$Lambda$3827/0x000000084067bc40.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2926/0x0000000840ca5840.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3762/0x000000084069f840.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer$$Lambda$27472/0x000000084445b840.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}

**Comment by PocketfulOfGeese** [comment]
While I admit I'm sick, and therefore exhausted from lack of sleep, and therefore may be missing something:

That log doesn't appear to implicate Astral Sorcery, but rather RefinedPipes. Is there more information for this to explain why it was opened here, or to point out a problem issue?

**Comment by ZiphonOfficial** [comment]
> While I admit I'm sick, and therefore exhausted from lack of sleep, and therefore may be missing something:
> 
> That log doesn't appear to implicate Astral Sorcery, but rather RefinedPipes. Is there more information for this to explain why it was opened here, or to point out a problem issue?

Hey man! You are absolutely fine. Take care of you first before you take care of anyone in this GitHub. I wasn't able to grab my log files for the server as my power was out basically the entire evening after I got home from work. I will send a pastebin with the full log later after my next shift ends (5PM CST). Get better soon! ❤️

P.S. Thank you for your patience.
