### ISSUE TITLE
Game Crash after interacting with the Lens for Starlight Transmutation

### ISSUE THREAD

**Issue by Xenorhaste** [HellFirePvP/AstralSorcery#1951]
After i tried to get starmetal ignot my game just crashed bc i interacted with the Lens

```
Time: 5/22/22 2:02 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:228)
	at hellfirepvp.astralsorcery.common.tile.base.TileEntitySynchronized.func_189518_D_(TileEntitySynchronized.java:65)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by PocketfulOfGeese** [comment]
Usually indicates the lens you linked has bad stats/missing stats/malformed data.

If this is for MC 1.16.5, don't use a lens, just link the collector directly (#1835).

If this is for MC 1.12, it's not a supported version, break and delete the lens, and use one that actually has stats. Don't use Building Gadgets to place the lenses, if you did.

In either case, resetting the Starlight Network should prevent the crash until you can break the lens (server config file).

**Comment by HellFirePvP** [comment]
The 1.12 version is no longer supported
