### ISSUE TITLE
NullPointerException on loading of world

### ISSUE THREAD

**Issue by ChickenF622** [HellFirePvP/AstralSorcery#1957]
This occurred after saving a world with crystals placed by me. Currently using the modpack FTB Endeavor v 1.9.0
Detail crash report: https://pastebin.com/NjtPYm9N

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/19/22 4:32 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at hellfirepvp.astralsorcery.common.crystal.CrystalCalculations.calculate(CrystalCalculations.java:36) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.crystal.CrystalCalculations.getThroughputMultiplier(CrystalCalculations.java:103) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.recBuildChain(TransmissionChain.java:108) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.recBuildChain(TransmissionChain.java:136) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.buildFromSource(TransmissionChain.java:74) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.buildNetworkChain(TransmissionChain.java:58) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionWorldHandler.buildNetworkChain(TransmissionWorldHandler.java:134) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionWorldHandler.tick(TransmissionWorldHandler.java:75) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.StarlightTransmissionHandler.tick(StarlightTransmissionHandler.java:47) ~[astralsorcery:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.worldTick(TickManager.java:63) ~[observerlib:1.16.5-1.5.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:95) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ftbjanitor.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ftbjanitor.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:minetogether.mixins.json:MixinIntegratedServer,pl:mixin:APP:minetogether.mixins.json:MixinIntegratedServerStopping,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ftbjanitor.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ftbjanitor.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

**Comment by iComputerfreak** [comment]
I also have this bug, playing FTB Presents: Interactions by Parts DX with Astral Sorcery 1.16.4-1.14.1.
In my case, the server crashes as soon as I link a Celestial Collector Crystal with a Crystal Prism. Normal lenses seem to work fine. I tried crafting a crystal, as well as cheating one in. Both crash the server.

The first time, the server just crashes, when I start it back up and link it again, the server crashes and is unable to start up again, as it just crashes every time I start it up.

My initial bug report in the modpack repo and my crash report stack trace is here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3556

**Comment by AndreiCatalinN** [comment]
Hi, I'm seeing something similar.

https://mclo.gs/EijzCXx#L17
