### ISSUE TITLE
[1.16.5] Crash

### ISSUE THREAD

**Issue by viminio** [HellFirePvP/AstralSorcery#1965]
net.minecraft.crash.ReportedException: Adding item to inventory
	at net.minecraft.entity.player.PlayerInventory.func_191971_c(PlayerInventory.java:298)
	at net.minecraft.entity.player.PlayerInventory.func_70441_a(PlayerInventory.java:246)
	at hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache.onPlayerConnect(EventHandlerCache.java:124)
	at net.minecraftforge.eventbus.ASMEventHandler_185_EventHandlerCache_onPlayerConnect_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3652/1616170221.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:30)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:232)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$27224/405768760.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: mc.player is not initialized! Probably not in game
	at org.anti_ad.mc.common.vanilla.Vanilla.player(Unknown Source)
	at org.anti_ad.mc.common.vanilla.Vanilla.container(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockedSlotKeeper.isOnlyHotbarFree(Unknown Source)
	at net.minecraft.entity.player.PlayerInventory.handler$zkn000$getEmptySlot(PlayerInventory.java)
	at net.minecraft.entity.player.PlayerInventory.func_70447_i(PlayerInventory.java)
	at net.minecraft.entity.player.PlayerInventory.func_70452_e(PlayerInventory.java:179)
	at net.minecraft.entity.player.PlayerInventory.func_191971_c(PlayerInventory.java:275)
	... 20 more

[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/9338416/latest.log)
[debug.log](https://github.com/HellFirePvP/AstralSorcery/files/9338417/debug.log)

**Comment by PocketfulOfGeese** [comment]
That log is a disaster of errors and missing files among damned near every mod in that pack. 

That it says a player doesn't exist to have the astral tome given to the player on first login is a problem with the instance going on, not Astral Sorcery.

Your instance is broken or busted.
