### ISSUE TITLE
Crashing when attunement

### ISSUE THREAD

**Issue by SomeRedApple** [HellFirePvP/AstralSorcery#1969]
Hey! So I've been playing Astral Sorcery and when I'm doing the attunement, I crash. This is really annoying and I found people saying that the issue was Traveler's Index, but I don't have it in my modpack. Tried the new version and the one before and still not working. Please help.

Here is the Minecraft Crash Report.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/10/22 10:06 PM
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:76) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:10) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStatsProvider.serializeNBT(PlayerStatsProvider.java:24) ~[?:3.0.4] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:127) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:136) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at hellfirepvp.astralsorcery.client.util.camera.CameraTransformerPlayerFocus.onStartTransforming(CameraTransformerPlayerFocus.java:40) ~[?:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.client.util.camera.ClientCameraManager.tick(ClientCameraManager.java:45) ~[?:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.renderTick(TickManager.java:84) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager$$Lambda$6811/319526972.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2983/1406666986.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3175/1474657733.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onRenderTickStart(BasicEventHooks.java:75) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:975) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1651795723.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:76) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStorage.writeNBT(PlayerStorage.java:10) ~[?:3.0.4] {re:classloading}
	at com.minecraftserverzone.weaponmaster.setup.capabilities.PlayerStatsProvider.serializeNBT(PlayerStatsProvider.java:24) ~[?:3.0.4] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:127) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:136) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
-- Entity being saved --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 381
	Entity Name: SomeRedApple
	Entity's Exact location: 499.61, 123.00, -674.52
	Entity's Block location: World: (499,123,-675), Chunk: (at 3,7,13 in 31,-43; contains blocks 496,0,-688 to 511,255,-673), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at hellfirepvp.astralsorcery.client.util.camera.CameraTransformerPlayerFocus.onStartTransforming(CameraTransformerPlayerFocus.java:40) ~[?:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.astralsorcery.client.util.camera.ClientCameraManager.tick(ClientCameraManager.java:45) ~[?:1.16.5-1.13.12] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.renderTick(TickManager.java:84) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager$$Lambda$6811/319526972.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2983/1406666986.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3175/1474657733.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['SomeRedApple'/381, l='ClientLevel', x=499.61, y=123.00, z=-674.52]]
	Chunk stats: Client Chunk Cache: 729, 95
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,68,208), Chunk: (at 0,4,0 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1816657 game time, 20237 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1651795723.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1037428256 bytes (989 MB) / 3182952448 bytes (3035 MB) up to 5816451072 bytes (5547 MB)
	CPUs: 8
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6240m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8%20(2).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		SkyVillage_1.0.0_1.16.5.jar                       |Sky Villages                  |skyvillages                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		astralsorcery-1.16-1.16.5-1.13.12.jar             |Astral Sorcery                |astralsorcery                 |1.16.5-1.13.12      |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |Manifest: NOSIGNATURE
		Hats-1.16.5-10.3.3.jar                            |Hats                          |hats                          |10.3.3              |DONE      |Manifest: NOSIGNATURE
		Mine_and_Slash_BETA-1.16.5-4.0.18.jar             |Mine and Slash                |mmorpg                        |NONE                |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		revsbetterstructures-1.16.5-1.4.2.jar             |Rev's Better Structures       |revsbetterstructures          |1.4.2               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |Manifest: NOSIGNATURE
		wonderful-enchantments-1.16.4-1.3.5.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.3.5               |DONE      |Manifest: NOSIGNATURE
		Space-BossTools-1.16.5-5.5e.jar                   |Space-BossTools               |boss_tools                    |5.5e                |DONE      |Manifest: NOSIGNATURE
		Dregora-1.76.jar                                  |Dregora                       |dregora                       |1.76                |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-8.4.7.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.7               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		TravelersBackpack-1.16.5-5.4.16.jar               |Traveler's Backpack           |travelersbackpack             |5.4.16              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.124-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.124    |DONE      |Manifest: NOSIGNATURE
		OpenTerrainGenerator-1.16.5-0.1.10.jar            |Open Terrain Generator        |otg                           |1.16.5-0.1.10       |DONE      |Manifest: NOSIGNATURE
		fantasy-forge-1.1.1.jar                           |Fantasy Mounts                |fantasy                       |1.0                 |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf                     |10.4.32             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		itemzoom-1.16.4-2.3.0.jar                         |Item Zoom                     |itemzoom                      |2.3.0               |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.16-5.1.8.jar                           |McJtyLib                      |mcjtylib                      |1.16-5.1.8          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.1.5.jar                        |RFToolsBase                   |rftoolsbase                   |1.16-2.1.5          |DONE      |Manifest: NOSIGNATURE
		ForgivingVoid_1.16.5-5.2.1.jar                    |Forgiving Void                |forgivingvoid                 |5.2.1               |DONE      |Manifest: NOSIGNATURE
		DarkUtilities-1.16.5-8.0.14.jar                   |Dark Utilities                |darkutils                     |8.0.14              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.6.1.jar                       |iChunUtil                     |ichunutil                     |10.6.1              |DONE      |Manifest: NOSIGNATURE
		Blocklings 7.0.0_b4.1 - 1.16.5.jar                |Blocklings                    |blocklings                    |7.0.0.4             |DONE      |Manifest: NOSIGNATURE
		rftoolspower-1.16-3.0.13.jar                      |RFToolsPower                  |rftoolspower                  |1.16-3.0.13         |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.2.10.jar                    |Paraglider                    |paraglider                    |1.3.2.10            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		untitledduckmod-0.3.0-forge.jar                   |Untitled Duck Mod             |untitledduckmod               |0.3.0               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.4.jar                 |Supplementaries               |supplementaries               |0.18.2              |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.4.335.jar                   |Tinkers' Construct            |tconstruct                    |3.3.4.335           |DONE      |Manifest: NOSIGNATURE
		River Treasures 1.0.2 - 1.16.5.jar                |River Treasures               |river_treasures               |1.0.2               |DONE      |Manifest: NOSIGNATURE
		rftoolsutility-1.16-3.1.16.jar                    |RFToolsUtility                |rftoolsutility                |1.16-3.1.16         |DONE      |Manifest: NOSIGNATURE
		Jade-1.16.4-2.8.3.jar                             |Jade                          |jade                          |2.8.3               |DONE      |Manifest: NOSIGNATURE
		baubles-1.8.7.1-1.16.5.jar                        |Baubles                       |baubles                       |1.8.7               |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.16.5-2.7.7.jar                     |Iron Furnaces                 |ironfurnaces                  |2.7.7               |DONE      |Manifest: NOSIGNATURE
		mining_dimension-1.16.5-1.0.6.jar                 |Mining World                  |mining_dimension              |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		Microcosm-1_16_5-1_5_1.jar                        |Microcosm                     |microcosm                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		weaponmaster-multi-forge-1.16.5-3.0.4.jar         |YDM's Weapon Master           |weaponmaster                  |3.0.4               |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.16.5-1.8.1.jar                |Dungeons Enhanced             |dungeons_enhanced             |1.8.1               |DONE      |Manifest: NOSIGNATURE
		Divine_Missions-1.16.5-1.0.1.jar                  |Divine Missions               |divine_missions               |NONE                |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.16-3.1.11.jar                    |RFToolsBuilder                |rftoolsbuilder                |1.16-3.1.11         |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.16.4-2.0.1.jar                  |Majrusz Library               |majrusz_library               |2.0.1               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		Cataclysm-0.20.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.38.jar                  |Inspirations                  |inspirations                  |1.2.3.38            |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.14.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |22.14.0             |DONE      |Manifest: NOSIGNATURE
		rftoolsstorage-1.16-2.0.19.jar                    |RFToolsStorage                |rftoolsstorage                |1.16-2.0.19         |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.5.2.jar                   |Storage Drawers               |storagedrawers                |8.5.2               |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |DONE      |Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		World_of_Exile-1.16.5-1.4.3.jar                   |Dungeons of Exile             |world_of_exile                |NONE                |DONE      |Manifest: NOSIGNATURE
		EverPotion-1.16.3-2.4.0.jar                       |EverPotion                    |everpotion                    |2.4.0               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.6.1.jar                             |Kiwi                          |kiwi                          |3.6.1               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |Manifest: NOSIGNATURE
		Library_of_Exile-1.16.5-1.2.3.jar                 |Library Of Exile              |library_of_exile              |NONE                |DONE      |Manifest: NOSIGNATURE
		Runelic-1.16.5-7.0.3.jar                          |Runelic                       |runelic                       |7.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.90.jar                  |GeckoLib                      |geckolib3                     |3.0.90              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 46cc3bd3-9438-4f65-948b-f5a1690ee1e4
	Kiwi Modules: 
		
	Launched Version: forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.94, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by PocketfulOfGeese** [comment]
Whatever this mod is the culprit, at the top of the stack here: minecraftserverzone.weaponmaster
