### ISSUE TITLE
Attack on titan minecraft mod crashes due to astral sorcery perk (1.12.2)

### ISSUE THREAD

**Issue by allforone33** [HellFirePvP/AstralSorcery#1970]
I know this version of the game is not supported but I was wondering if there was a way to disable perks that cause these sorts of issues in the 1.12.2 version of the mod, as I was looking for a sort of work around to this issue.

java.lang.NullPointerException
    at net.minecraft.network.datasync.EntityDataManager.get(EntityDataManager.java:150)
    at net.minecraft.entity.projectile.EntityArrow.getIsCritical(EntityArrow.java:636)
    at hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritMultiplier.onArrowCt(AttributeCritMultiplier.java:42)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_53_AttributeCritMultiplier_onArrowCt_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at lyon.aom.packets.both.spawn_projectile_reply.PacketSpawnProjectileReplyHandler$3.run(PacketSpawnProjectileReplyHandler.java:75)
    at lyon.aom.utils.handlers.QueuedTaskHandler.executeQueuedRunnables(QueuedTaskHandler.java:63)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_122_QueuedTaskHandler_executeQueuedRunnables_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)

I downgraded to a previous version of the mod (1.9.4,) but than the same thing happened at startup, this time for superior shields.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Superior Shields (superiorshields)
Caused by: java.lang.NoClassDefFoundError: hellfirepvp/astralsorcery/common/constellation/perk/attribute/PerkAttributeType
    at epicsquid.superiorshields.proxy.CommonProxy.preInit(CommonProxy.java:20)
    at epicsquid.superiorshields.proxy.ClientProxy.preInit(ClientProxy.java:12)
    at epicsquid.superiorshields.SuperiorShields.preInit(SuperiorShields.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.ClassNotFoundException: hellfirepvp.astralsorcery.common.constellation.perk.attribute.PerkAttributeType
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 52 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 54 more

**Comment by PocketfulOfGeese** [comment]
Some other mod is messing with something causing that to trigger, ultimately, since passing a null value into that shouldn't be possible otherwise. Sadly, support for 1.12 is indeed deprecated.

**Comment by allforone33** [comment]
> Some other mod is messing with something causing that to trigger, ultimately, since passing a null value into that shouldn't be possible otherwise. Sadly, support for 1.12 is indeed deprecated.

Is that for the one with superior shields or attack on minecraft mod? Or are both mods the offenders and not Astral Sorcery?

**Comment by PocketfulOfGeese** [comment]
The first. Second is looking for a class in AS that doesnt exist in the much earlier version.

If you can reliably trigger the crash, a binary search is your best bet. If not, shrug.

**Comment by allforone33** [comment]
it happens whenever I try and use the gear, is there anyway to fix this issue in a sort of work-around-way? Like going into the jar file and messing with the settings?
