### ISSUE TITLE
Problem with the "Traveler's Index" mod when trying to run the attunement altar animation

### ISSUE THREAD

**Issue by sysker** [HellFirePvP/AstralSorcery#1981]
Using the astral in a mod pack, when I got on the attunement altar to enchant myself the game crashed saying "Exception caught during firing event: Saving entity NBT". I was able to fix it by removing the "Traveler's Index" mod. 

I don't really know to which point it's a problem of the astral, the other mod or both, but in case it could be useful to solve possible incompatibilities with other mods, here is the crash report that the game gave me:

 ---- Minecraft Crash Report ----
---------------------------------------------------------------------------------------
// There are four lights!

Time: 19/01/23 1:49
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:32) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:16) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:29) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:14) ~[?:1.16.4-1.0.2] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:113) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:122) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:EntityMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinEntity,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.EntityAccessor,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_fluid_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinEntity,pl:mixin:A}
	at hellfirepvp.astralsorcery.client.util.camera.CameraTransformerPlayerFocus.onStartTransforming(CameraTransformerPlayerFocus.java:40) ~[?:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.client.util.camera.ClientCameraManager.tick(ClientCameraManager.java:45) ~[?:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.renderTick(TickManager.java:84) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager$$Lambda$4320/874458410.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2859/224950719.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3105/261371975.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onRenderTickStart(BasicEventHooks.java:61) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:975) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$506/72893188.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:32) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:16) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:29) ~[?:1.16.4-1.0.2] {re:classloading}
	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:14) ~[?:1.16.4-1.0.2] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:113) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:122) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
-- Entity being saved --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 105
	Entity Name: Arkhrai
	Entity's Exact location: -34.71, 84.00, 65.49
	Entity's Block location: World: (-35,84,65), Chunk: (at 13,5,1 in -3,4; contains blocks -48,0,64 to -33,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:EntityMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinEntity,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.EntityAccessor,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_fluid_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinEntity,pl:mixin:A}
	at hellfirepvp.astralsorcery.client.util.camera.CameraTransformerPlayerFocus.onStartTransforming(CameraTransformerPlayerFocus.java:40) ~[?:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.client.util.camera.ClientCameraManager.tick(ClientCameraManager.java:45) ~[?:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.renderTick(TickManager.java:84) ~[?:1.16.5-1.5.3] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager$$Lambda$4320/874458410.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2859/224950719.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3105/261371975.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Arkhrai'/105, l='ClientLevel', x=-34.71, y=84.00, z=65.49]]
	Chunk stats: Client Chunk Cache: 1024, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-47,63,48), Chunk: (at 1,3,0 in -3,3; contains blocks -48,0,48 to -33,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3334 game time, 15450 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:458) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:sulfuric.mixins.json:client.world.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:blue_skies.mixins.json:ClientWorldMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:client.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$506/72893188.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

**Comment by sysker** [comment]
I forgot to mention that I was using version 1.16.5-1.14.1 of the astral mod.

**Comment by luna6667** [comment]
Known issue with travellers index #1594
