### ISSUE TITLE
Coding error: using Scala Arrays not Java Arrays!

### ISSUE THREAD

**Issue by radfast** [HellFirePvP/AstralSorcery#250]
Looks like you used the wrong import, guys :)

>
    [17:41:47] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Load@7ee502f6:
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at hellfirepvp.astralsorcery.common.data.server.ServerData.defaultToConfig(ServerData.java:155) ~[ServerData.class:?]
	at hellfirepvp.astralsorcery.common.data.server.ServerData.loadDataFromFile(ServerData.java:150) ~[ServerData.class:?]
	at hellfirepvp.astralsorcery.common.data.server.ServerData.reloadDataFromSaveHandler(ServerData.java:71) ~[ServerData.class:?]
	at hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer.onLoad(EventHandlerServer.java:103) ~[EventHandlerServer.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_833_EventHandlerServer_onLoad_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:246) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:783) [MinecraftServer.class:?]
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.registerPlanet(WorldUtil.java:589) [WorldUtil.class:?]
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.onServerStarting(GalacticraftCore.java:470) [GalacticraftCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:878) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:296) [FMLCommonHandler.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at Reflector.callBoolean(Reflector.java:735) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:205) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

This is your issue, [not a Galacticraft issue](https://github.com/micdoodle8/Galacticraft/issues/2916).  We're happy to help resolve it if it's a mod conflict, but I think it's simply that you imported the wrong ```Arrays```

**Comment by radfast** [comment]
Sorry, just seen this was fixed in https://github.com/HellFirePvP/AstralSorcery/commit/060184005d4d14edeba5a06ba906c40f8bbd89e6

**Comment by HellFirePvP** [comment]
Yea... this has already been adressed quite a while ago.
