### ISSUE TITLE
crashing while attempting to craft a lens in 1.11 version 1.4.5

### ISSUE THREAD

**Issue by witherlink13** [HellFirePvP/AstralSorcery#255]
ive crashed 10 times on multiple words attempting to craft the lens the crash report always comes up with this "Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at hellfirepvp.astralsorcery.common.item.crystal.CrystalProperties.applyCrystalProperties(CrystalProperties.java:183)
	at hellfirepvp.astralsorcery.common.crafting.altar.recipes.LensRecipe.getOutput(LensRecipe.java:64)
	at hellfirepvp.astralsorcery.common.tile.TileAltar.finishCrafting(TileAltar.java:238)
	at hellfirepvp.astralsorcery.common.tile.TileAltar.doTryCraft(TileAltar.java:220)
	at hellfirepvp.astralsorcery.common.tile.TileAltar.func_73660_a(TileAltar.java:123)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)"

**Comment by HellFirePvP** [comment]
Can you provide a screenshot of the crystal you've used to craft the lens? More specifically its properties.

**Comment by witherlink13** [comment]
it didnt have any properties when i mined it which is the problem

**Comment by HellFirePvP** [comment]
Well. yea. a crystal without properties causes this - most likely on more occasions than that aswell.

What type of server are you running? Forge? If so which version? What pack are you running? Anything that modifies EntityItems? Did you pick it up with some sort of instant-pickup magnet that might've removed the necessary data?

**Comment by witherlink13** [comment]
it isnt a server i think journeymap or any other mod i have is the cause of it being considered one

**Comment by Doomgull** [comment]
@witherlink13 every minecraft instance has a server and a client instance, even in single player. It's been that way for a long while now. Doesn't change that the answer in that case should be "Singleplayer". Also need the rest of the information.

**Comment by witherlink13** [comment]
its  a custom pack i have using nether ex, ad inferos, journeymap, NEI, tinkers and some addons for it, project e, bloodmagic, botania, exteme reactors, thermal dynamics foundation and expansion, quark and an addon for it.
