### ISSUE TITLE
[1.12] Extra Utils crash

### ISSUE THREAD

**Issue by DaggerTM** [HellFirePvP/AstralSorcery#258]
```
java.lang.ClassCastException: hellfirepvp.astralsorcery.common.world.WorldProviderBrightnessInj cannot be cast to com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.resetChunkBlocks(WorldProviderSpecialDim.java:127)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.releaseChunk(WorldProviderSpecialDim.java:148)
	at com.rwtema.extrautils2.quarry.TileQuarry.getNewChunk(TileQuarry.java:414)
	at com.rwtema.extrautils2.quarry.TileQuarry.advance(TileQuarry.java:409)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:307)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by HellFirePvP** [comment]
#238
