### ISSUE TITLE
[1.12.2] Gen Error

### ISSUE THREAD

**Issue by BuilderDan** [HellFirePvP/AstralSorcery#337]
Getting this error when I try to start my server, works fine with client:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundFixPatchingLoader (AmbientSounds v2.1.0 mc1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.7.jar)
  AstralCore (astralsorcery-1.12.2-1.7.1.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  LittlePatchingLoader (LittleTiles v1.5.0-pre39 mc1.12.2.jar)
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.68-universal.jar)
  ComfortsLoadingPlugin (comforts-1.12.2-0.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2 (1).jar)
  FMLLoadingPlugin (lilliputian-0.0.1-ALPHA.jar)
  LoadingPlugin (Quark-r1.3-114.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.b128.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1 (1).jar)
  LibrarianLib Plugin (librarianlib-1.12-4.1.jar)
  CreativePatchingLoader (CreativeCore v1.9.4 mc1.12.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12-1.9 (1).jar)
  Extra Alchemy ASM (extraalchemy-0.3.5-release.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/7/17 2:06 AM
Description: Exception in server tick loop

java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    net/minecraft/server/management/PlayerInteractionManager.getBlockReachDistance()D @11: dmul
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @11
    flags: { }
    locals: { 'net/minecraft/server/management/PlayerInteractionManager' }
    stack: { 'net/minecraft/entity/player/EntityPlayerMP', double, double_2nd }
  Bytecode:
    0x0000000: 2ab4 0048 2ab4 0048 b802 376b b200 c1b6
    0x0000010: 00c5 b900 cb01 002a b400 48b8 023b af  

	at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:42)
	at net.minecraftforge.common.util.FakePlayerFactory.get(FakePlayerFactory.java:61)
	at hellfirepvp.astralsorcery.common.CommonProxy.getASFakePlayerServer(CommonProxy.java:262)
	at hellfirepvp.astralsorcery.common.util.MiscUtils.breakBlockWithoutPlayer(MiscUtils.java:172)
	at hellfirepvp.astralsorcery.common.tile.TileOreGenerator.shouldRefresh(TileOreGenerator.java:79)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:569)
	at minestrapp.worldgen.MStoneGen.generate(MStoneGen.java:82)
	at minestrapp.worldgen.MOreGen.generate(MOreGen.java:155)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by HellFirePvP** [comment]
Not on my end. Remove mods with coremods until it doesn't happen anymore. Post that to that mod's issue tracker then.
