### ISSUE TITLE
Unrecoverable game crash in v1.4.5 (MC 1.10.2) Simple Life 2

### ISSUE THREAD

**Issue by MyDaysBoy** [HellFirePvP/AstralSorcery#347]
AS version: 1.4.5
MC version 1.10.2

In The Simple Life 2 mod pack I needed a cake to make a Winter Rune from Botania and the only way is villager trade or using an AS lens to make a cake from a pumpkin. No farmers found after 8 villages so I built the Starlight Crafting Alter and placed the ingredients and started the process to create the lens. The starlight pulsed for 5-10 seconds and got the following error (luckily I had backed up the game just 2 hours prior):

java.lang.NullPointerException: Ticking block entity
	at hellfirepvp.astralsorcery.common.item.crystal.CrystalProperties.applyCrystalProperties(CrystalProperties.java:182)
	at hellfirepvp.astralsorcery.common.crafting.altar.recipes.LensRecipe.getOutput(LensRecipe.java:63)
	at hellfirepvp.astralsorcery.common.tile.TileAltar.finishCrafting(TileAltar.java:236)
	at hellfirepvp.astralsorcery.common.tile.TileAltar.doTryCraft(TileAltar.java:218)
	at hellfirepvp.astralsorcery.common.tile.TileAltar.func_73660_a(TileAltar.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Full crash log at: https://pastebin.com/wTEG8pzm

Cannot re-open the world now, it crashes immediately. Same error as above each time.

**Comment by Doomgull** [comment]
Need to know the stats on the involved crystals. Were they quest rewards? Seems like something wasn't properly assigned as a trait.

**Comment by MyDaysBoy** [comment]
The crystals were either quest rewards or I got them from the chest under monument that had the floating crystal (where the wand & crafting table were made).
