### ISSUE TITLE
[1.12.2] Collision w/ OpenTerrainGenerator

### ISSUE THREAD

**Issue by T145** [HellFirePvP/AstralSorcery#361]
Using latest Forge and Java 8 152:

```
[17:34:28] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141) ~[bbs.class:?]
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77) ~[bbs.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_180513_a(OTGChunkGenerator.java:419) ~[OTGChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:307) ~[on.class:?]
	at hellfirepvp.astralsorcery.common.world.structure.StructureTreasureShrine.getGenerationPosition(StructureTreasureShrine.java:82) ~[StructureTreasureShrine.class:?]
	at hellfirepvp.astralsorcery.common.world.WorldGenAttributeCommon.generate(WorldGenAttributeCommon.java:57) ~[WorldGenAttributeCommon.class:?]
	at hellfirepvp.astralsorcery.common.world.structure.WorldGenAttributeStructure.generate(WorldGenAttributeStructure.java:69) ~[WorldGenAttributeStructure.class:?]
	at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.generateWithLastKnownVersion(AstralWorldGenerator.java:107) ~[AstralWorldGenerator.class:?]
	at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.generate(AstralWorldGenerator.java:85) ~[AstralWorldGenerator.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
```

**Comment by Doomgull** [comment]
#358
