### ISSUE TITLE
[1.12.2] Crash Ritual Horologium?

### ISSUE THREAD

**Issue by Kuroe88** [HellFirePvP/AstralSorcery#490]
Basically i logged out. A couple of days later i try to log in and bam, crash when entering the world.

Here is the first part of the crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b129.jar)
  LoadingPlugin (sampler-1.73.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.2-Anarchy.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 1/7/18 3:01 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at hellfirepvp.astralsorcery.common.constellation.effect.CEffectPositionListGen.getRandomElementByChance(CEffectPositionListGen.java:68)
	at hellfirepvp.astralsorcery.common.constellation.effect.aoe.CEffectHorologium.playMainEffect(CEffectHorologium.java:68)
	at hellfirepvp.astralsorcery.common.tile.TileRitualPedestal$TransmissionReceiverRitualPedestal.doMainEffect(TileRitualPedestal.java:730)
	at hellfirepvp.astralsorcery.common.tile.TileRitualPedestal$TransmissionReceiverRitualPedestal.update(TileRitualPedestal.java:639)
	at hellfirepvp.astralsorcery.common.starlight.network.StarlightUpdateHandler.tick(StarlightUpdateHandler.java:45)
	at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.worldTick(TickManager.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_932_TickManager_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by Doomgull** [comment]
Forge version, full modpack and versions. Next time please put the full log into pastebin/hastebin or the like and link that instead of putting a partial directly into the ticket.

**Comment by Kuroe88** [comment]
Sorry, here is more info. Thanks for the reply. :)

MineCraft 1.12.2 Forge 1.12.2-14.23.1.2566

Pastebin of the full crash report
https://pastebin.com/kkYRcF4b

Mod List
https://imgur.com/a/YXBQM

**Comment by flamefurno** [comment]
Hey there!
We are running this version of the mod on our direwolf server and where wondering if this bug would have any impact on it? Thanks in advance!

**Comment by Doomgull** [comment]
Since we've only received one report, my answer is: if it happens, it affects you, otherwise, no.
