### ISSUE TITLE
PerkCreationBreedables tick crash

### ISSUE THREAD

**Issue by cleverca22** [HellFirePvP/AstralSorcery#496]
```
[04:48:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@2f11b4d9:
java.lang.NullPointerException: null
        at hellfirepvp.astralsorcery.common.constellation.perk.impl.PerkCreationBreedables.onPlayerTick(PerkCreationBreedables.java:52) ~[PerkCreationBreedables.class:?]
        at hellfirepvp.astralsorcery.common.constellation.perk.PlayerPerkHandler.tick(PlayerPerkHandler.java:43) ~[PlayerPerkHandler.class:?]
        at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.playerTick(TickManager.java:92) ~[TickManager.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1227_TickManager_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368) [FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```
https://github.com/HellFirePvP/AstralSorcery/blob/3a3175966dd22921573b77ba3668a97beeea5acc/src/main/java/hellfirepvp/astralsorcery/common/constellation/perk/impl/PerkCreationBreedables.java#L51-L52
https://minecraft.curseforge.com/projects/animania

i believe one of the chickens in this mod is returning null from its `createChild` method, causing astral sorcery to crash in its tick handler, so i get booted any time i get near a chicken

this bug can also trigger while in spectator mode, and i can see a number of my current perks wreaking havoc in my wake as i phase thru walls to diagnose server problems

**Comment by Doomgull** [comment]
Did you also open a bug report with animania?

**Comment by cleverca22** [comment]
havent bothered to find their github yet
