### ISSUE TITLE
Whelp.

### ISSUE THREAD

**Issue by Thornstromb** [HellFirePvP/AstralSorcery#537]
java.lang.NullPointerException: Exception ticking world
    at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:218)
    at hellfirepvp.astralsorcery.common.tile.base.TileEntitySynchronized.func_189518D(TileEntitySynchronized.java:65)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)

occurs ONLY ON SERVER when placing or redirecting the lens, crashing the server. Singleplayer unaffected.

**Comment by Doomgull** [comment]
Would be great to know what versions were involved, and the full crash log thrown up into pastebin and linked, or the like.

If you're not on AS 1.8.5, update to it and see if it replicates.

**Comment by HellFirePvP** [comment]
Its properties are null. Check what pack you are playing and report it to them how you got a lens or crystal without properties.

**Comment by Thornstromb** [comment]
ah thank you for prompt answer Hellfire will do
