### ISSUE TITLE
Server Tick Loop Celestial Gateway

### ISSUE THREAD

**Issue by CLASnipe** [HellFirePvP/AstralSorcery#622]
We are running Sevtech Ages 3.0.6 we started noticing a bit of lag and decided to restart and now if just crashes

Description: Exception in server tick loop
 
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
    at net.minecraft.world.World.func_147448_a(World.java:1943)
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:854)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
    at net.minecraft.world.World.func_72964_e(World.java:309)
    at net.minecraft.world.World.func_175726_f(World.java:304)
    at net.minecraft.world.World.func_175625_s(World.java:2396)
    at hellfirepvp.astralsorcery.common.util.MiscUtils.getTileAt(MiscUtils.java:61)
    at hellfirepvp.astralsorcery.common.data.world.data.GatewayCache.onLoad(GatewayCache.java:81)
    at hellfirepvp.astralsorcery.common.data.world.WorldCacheManager.loadAndCache(WorldCacheManager.java:108)
    at hellfirepvp.astralsorcery.common.data.world.WorldCacheManager.getOrLoadData(WorldCacheManager.java:54)
    at hellfirepvp.astralsorcery.common.auxiliary.CelestialGatewaySystem.loadWorldCache(CelestialGatewaySystem.java:163)
    at hellfirepvp.astralsorcery.common.auxiliary.CelestialGatewaySystem.onWorldInit(CelestialGatewaySystem.java:94)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1449_CelestialGatewaySystem_onWorldInit_Load.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at java.lang.Thread.run(Thread.java:748)

**Comment by CLASnipe** [comment]
[http://prntscr.com/j4l9bm](url)

This is a temporary fix found in the forge config. Change those from False to true removes the erroring tile entities before crashing the server. (Note: Resets after every update)

**Comment by Doomgull** [comment]
And what did it remove on launch?

**Comment by CLASnipe** [comment]
it removed the broken tile entities that were causing the crash

**Comment by Doomgull** [comment]
My questions was more "Was it the gateway erroring, or was it something in a chunk with a gateway erroring" on the TE thing.

And do you mean the gateway preview images?

**Comment by HunterAshh** [comment]
I had to go in and delete the gateway dat files in the different dims to get the server to start again. Using forge's removing ticking entities option did nothing.

**Comment by Jo-Mamma75** [comment]
@HellFirePvP 
So I see you closed this issue but we're having basically the same problem on one of our Patron servers.  The player has not cheated the lens in and did not receive it by any other means (or so he states).  Here is the crash log if you would like to have a look at it.

[https://pastebin.com/9vEZjv9X](url)

**Comment by HellFirePvP** [comment]
Different issue. The lens is missing NBT data. In whatever way you got that lens, it's broken and the way of obtaining that one should be avoided at all cost.
