### ISSUE TITLE
Crash Report AstralSorcery-1.12.2-1.8.7

### ISSUE THREAD

**Issue by GreyMamoN** [HellFirePvP/AstralSorcery#655]
Crash Report AstralSorcery-1.12.2-1.8.7
On version AstralSorcery-1.12.2-1.8.5 there is no such error

[21:53:49] [Server thread/FATAL]: The following problems were captured during this phase
[21:53:49] [Server thread/ERROR]: Caught exception from astralsorcery (Astral Sorcery)
java.lang.IllegalStateException: Too late to add dynamic configuration entries
	at hellfirepvp.astralsorcery.common.data.config.Config.addDynamicEntry(Config.java:109) ~[Config.class:?]
	at hellfirepvp.astralsorcery.common.world.attributes.GenAttributeRockCrystals.<init>(GenAttributeRockCrystals.java:74) ~[GenAttributeRockCrystals.class:?]
	at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.setupAttributes(AstralWorldGenerator.java:56) ~[AstralWorldGenerator.class:?]
	at hellfirepvp.astralsorcery.common.CommonProxy.init(CommonProxy.java:233) ~[CommonProxy.class:?]
	at hellfirepvp.astralsorcery.AstralSorcery.init(AstralSorcery.java:81) ~[AstralSorcery.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[forge.jar:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[server.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[server.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[server.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[server.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[server.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[server.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:755) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[21:53:49] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)

Caused by: java.lang.IllegalStateException: Too late to add dynamic configuration entries
	at hellfirepvp.astralsorcery.common.data.config.Config.addDynamicEntry(Config.java:109) ~[Config.class:?]
	at hellfirepvp.astralsorcery.common.world.attributes.GenAttributeRockCrystals.<init>(GenAttributeRockCrystals.java:74) ~[GenAttributeRockCrystals.class:?]
	at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.setupAttributes(AstralWorldGenerator.java:56) ~[AstralWorldGenerator.class:?]
	at hellfirepvp.astralsorcery.common.CommonProxy.init(CommonProxy.java:233) ~[CommonProxy.class:?]
	at hellfirepvp.astralsorcery.AstralSorcery.init(AstralSorcery.java:81) ~[AstralSorcery.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[forge.jar:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[server.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[server.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[server.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280) ~[forge.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258) ~[forge.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[server.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[server.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[server.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[server.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:755) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Doomgull** [comment]
It is almost like the very top ticket when you opened yours was addressing the exact same issue. #654
