### ISSUE TITLE
Gateway crash

### ISSUE THREAD

**Issue by Xandaros** [HellFirePvP/AstralSorcery#678]
Hey,
I'm playing SevTech on a remote server and crashed. I'm not exactly sure what I did, but I believe I was just walking around. Considering the error, I probably walked onto a celestial gateway.

After logging back in, I crashed again immediately. On a third try, I cleared the log just before joining to get a log that is as clean as possible: http://paste.atlauncher.com/view/2ab7ef53

The error I believe is causing me to crash:
```
[02/5/2018 21:57:10 PM] java.lang.NullPointerException: Unexpected error
[02/5/2018 21:57:10 PM] 	at hellfirepvp.astralsorcery.client.event.ClientGatewayHandler.onClientTick(ClientGatewayHandler.java:65)
[02/5/2018 21:57:10 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2044_ClientGatewayHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
[02/5/2018 21:57:10 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[02/5/2018 21:57:10 PM] 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[02/5/2018 21:57:10 PM] 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
[02/5/2018 21:57:10 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
[02/5/2018 21:57:10 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
[02/5/2018 21:57:10 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[02/5/2018 21:57:10 PM] 	at net.minecraft.client.main.Main.main(SourceFile:123)
[02/5/2018 21:57:10 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02/5/2018 21:57:10 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02/5/2018 21:57:10 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02/5/2018 21:57:10 PM] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02/5/2018 21:57:10 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02/5/2018 21:57:10 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Which is referring to this line: https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/client/event/ClientGatewayHandler.java#L65

I'm not exactly sure what is null here. The only thing I can think of is the player, which is being dereferenced with `player.world`. I'm not too familiar with Minecraft mods - does the client tick before the player object is available? That seems a bit weird to me, but I consistently crash when joining.

After an operator teleported me away from the gateway, I was able to log in again.

**Comment by Doomgull** [comment]
You disconnected from the server long before that crash actually triggered, and fact the login between the disconnection and where that crashes is full of network errors. What was at the location where you originally disconnected?

gamestages]: Syncing recived for **MINECRAFTUSERNAME**
[02/5/2018 21:56:25 PM] [main/INFO] [Item Stages]: Syncing 16145 items with JEI!.
[02/5/2018 21:56:33 PM] [main/INFO] [Item Stages]: Finished JEI Sync, took 7827ms. 5367 hidden, 10778 shown.
[02/5/2018 21:56:33 PM] [21:56:33] [Netty Epoll Client IO #0/INFO] [Astral Sorcery]: [AstralSorcery] Cleaning client cache...
[02/5/2018 21:56:33 PM] [21:56:33] [Netty Epoll Client IO #0/INFO] [Astral Sorcery]: [AstralSorcery] Cleared cached client data! Disconnected from server.

**Comment by Xandaros** [comment]
I like the `uuuhhhh.... wtf.` label :D

Judging by the `Fixed/Added next update`, you already fixed it, but here's what I think is happening: Because SevTech is such a gigantic pack, it loads very slowly on my machine. In fact, it can take more than 10 seconds to just change dimension and changing dimensions has triggered this crash before.

I also do get a desync when I initially log in or change dimension. I can't see blocks you can't see in Age 0, for example. This will sort itself out after a couple seconds.

I think the client might start ticking before the world is properly stored in the player object. (Assuming your new check works :P)
