### ISSUE TITLE
Crash when using Telescope

### ISSUE THREAD

**Issue by Sakata-MC** [HellFirePvP/AstralSorcery#725]
I get crashes when moving the telescope. Imagine it is due to one of the constellations that I don't have yet.

This has occurred (reproducible) 4 times now, each time using the telescope as only person logged in.

```
[20:50:30] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_171]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_171]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more
```
[crash-2018-05-24_20.50.30-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/2037580/crash-2018-05-24_20.50.30-server.txt)

**Comment by Doomgull** [comment]
Probably #702, will wait for HellFire's confirmation, however.

**Comment by HellFirePvP** [comment]
That issue doesn't have any correlation to issue 702; that is "just" the ever recurring CME with chunk loading & unloading...

**Comment by HellFirePvP** [comment]
Well, given that information, nothing even points at any part of AS directly that's connected with the supposed action you took to "cause this"

**Comment by Doomgull** [comment]
@Sakata-MC check with 1.9.1 and see if it still occurs for you, when you get the chance.

**Comment by sn00p16** [comment]
Can confirm this on my server too. Same crash log, give or take. Can look at several constellations but when one comes into view the server crashes and dies and all players are kicked out through timeout.

At work right now, but can try and get more information later this evening.

**Comment by HellFirePvP** [comment]
Did some work on network traffic and its synchronization to the main thread. Should this persist after AstralSorcery v1.10 - the next release - then please comment again here.

**Comment by mille449** [comment]
Getting this problem with Horologium in the telescope.

**Comment by Doomgull** [comment]
@mille449 yes...because 1.10 isn't out yet. So the fix isn't out yet.

**Comment by Doomgull** [comment]
Closing this one, if issue still re-occurs with a 1.10.x or later version, someone reopen.

**Comment by alex2069** [comment]
I've been getting this in SevTech 3.1.1 (crash when using Telescope).
- Which is using astralsorcery-1.12.2-1.10.11
- Additionally I've added gottagofast-1.1
- And re-enabled overworld to the constellation drawing configs `skySupportedDimensions` on server/client (standard SevTech has it turned off in case people want to use Optifine or something)

I got it when trying to find Horologium (I'd discovered all major/minor constellations except for that one - haven't got an Iridescent Altar yet). Attuned to Vicio ~level 25 or so.

This has happened probably 4-5 times now. I'd open the telescope and just spam-click the right arrow button to try to find a blank one. It seems to move through a couple of constellations and then the server dies.

Not sure if it will help, but I'd been recording the days I was checking:

Date | Day | Visible | Mod-Day |  
-- | -- | -- | -- | --
10/07/0005 | 2015 | NO | 35 |  
11/07/0005 | 2016 | NO | 0 |  
12/07/0005 | 2017 | ? | 1 | Crashed
13/07/0005 | 2018 | ? | 2 | Didn't check
14/07/0005 | 2019 | ? | 3 | Didn't check
15/07/0005 | 2020 | ? | 4 | Didn't check
16/07/0005 | 2021 | ? | 5 | Didn't check
17/07/0005 | 2022 | ? | 6 | Didn't check
18/07/0005 | 2023 | ? | 7 | Didn't check
19/07/0005 | 2024 | YES | 8 | Coincidentally found

**Date** is from a Calendar bauble.
**Day** is from `/time query day`

It had actually crashed a few days prior to the one above as well, so after the second crash on that day (IRL day) I didn't check again until it was just me online in case it crashed it again. Very coincidentally found it next I checked (woo!).

Stack trace:
```
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

Full log:
[crash-2019-04-23_19.45.28-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3111949/crash-2019-04-23_19.45.28-server.txt)

**Comment by Doomgull** [comment]
Telescope cme had some changes in a more recent version than 1.10.11. Uograde and test again.
