### ISSUE TITLE
Updating to 1.9.0 - java.lang.ArrayIndexOutOfBoundsException: 32767

### ISSUE THREAD

**Issue by laneyfamily** [HellFirePvP/AstralSorcery#760]
Getting error when upgrading to 1.9.0
All other mods unchanged, downgrade to 1.8.10 crash does not happen

https://paste.dimdev.org/cayudarofa.mccrash

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
    at erebus.items.ItemErebusFood.getContainerItem(ItemErebusFood.java:116)
    at erebus.items.ItemErebusFood.hasContainerItem(ItemErebusFood.java:133)
    at erebus.items.ItemErebusFood.getItemStackLimit(ItemErebusFood.java:138)
    at net.minecraft.item.ItemStack.getMaxStackSize(ItemStack.java:248)
    at hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted(EnchantmentUpgradeHelper.java:176)
    at hellfirepvp.astralsorcery.common.enchantment.amulet.PlayerAmuletHandler.attachAmuletItemCapability(PlayerAmuletHandler.java:38)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3503_PlayerAmuletHandler_attachAmuletItemCapability_AttachCapabilitiesEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:658)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:640)
    at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
    at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
    at net.minecraft.item.ItemStack.<init>(ItemStack.java:98)
    at flaxbeard.cyberware.api.CyberwareAPI.getLinkedWare(CyberwareAPI.java:333)
    at flaxbeard.cyberware.api.CyberwareAPI.isCyberware(CyberwareAPI.java:260)
    at flaxbeard.cyberware.common.handler.MiscHandler.handleCyberwareTooltip(MiscHandler.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3747_MiscHandler_handleCyberwareTooltip_ItemTooltipEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:325)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:889)
    at net.minecraft.client.Minecraft.lambda$null$3(Minecraft.java:593)
    at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.util.stream.ReferencePipeline.collect(Unknown Source)
    at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$5(Minecraft.java:596)
    at net.minecraft.client.util.SearchTree.index(SourceFile:49)
    at net.minecraft.client.util.SearchTree.add(SourceFile:44)
    at java.util.ArrayList.forEach(Unknown Source)
    at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:603)
    at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1079)
    at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
    at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
    at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3923)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Doomgull** [comment]
#747

Also, don't copy chunks of the log into the ticket. You already included a link to it, don't make it annoying to deal with via email or mobile.

**Comment by laneyfamily** [comment]
Sorry about that, I was not aware it would blast that chunk in email, I have seen different gits request post part of log, post the crash report, post mod list, etc, so did not want to not provide enough info.  If I report another issue I will be sure to only sum it up and provide the crashlog.  Thank you for the feedback and hope you have a great rest of your day

PS; Love your mod by the way, you are a talented creator.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
