### ISSUE TITLE
Crash using the evorsio cape when its effect attemps to break certain tile entities

### ISSUE THREAD

**Issue by Yarillo4** [HellFirePvP/AstralSorcery#790]
AS: astralsorcery-1.12.2-1.8.10
Forge: 14.23.4.2705
MC: 1.12.2

Using the latest Sevtech modpack. 

I think I was breaking a hopper ? A chalice might have been in the area too

[Crash log](http://upaste.me/ac344999145908ec2)

```
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at hellfirepvp.astralsorcery.common.block.BlockChalice.addDestroyEffects(BlockChalice.java:71)
	at hellfirepvp.astralsorcery.common.constellation.cape.impl.CapeEffectEvorsio.playBlockBreakParticles(CapeEffectEvorsio.java:80)
	at hellfirepvp.astralsorcery.common.network.packet.server.PktParticleEvent.lambda$triggerClientside$0(PktParticleEvent.java:111)
	at hellfirepvp.astralsorcery.client.ClientScheduler.tick(ClientScheduler.java:49)
	at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.clientTick(TickManager.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2125_TickManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by HellFirePvP** [comment]
Clientside crash due to desync.

**Comment by Yarillo4** [comment]
Thanks for the quick response :)
