### ISSUE TITLE
Yet another negative value crash.

### ISSUE THREAD

**Issue by ruifung** [HellFirePvP/AstralSorcery#798]
Judging by the function it errorred in, looks like something related to the previous negative world time issue? Although this time, I don't even know which world it is. Just putting this here just in case.

This was a crash.
```
Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -7
    at hellfirepvp.astralsorcery.common.constellation.distribution.WorldSkyHandler.getCurrentMoonPhase(WorldSkyHandler.java:288)
    at hellfirepvp.astralsorcery.common.registry.RegistryConstellations$2.doesShowUp(RegistryConstellations.java:489)
    at hellfirepvp.astralsorcery.common.constellation.distribution.WorldSkyHandler.doConstellationIteration(WorldSkyHandler.java:204)
    at hellfirepvp.astralsorcery.common.constellation.distribution.WorldSkyHandler.scheduleDayProgression(WorldSkyHandler.java:174)
    at hellfirepvp.astralsorcery.common.constellation.distribution.WorldSkyHandler.tick(WorldSkyHandler.java:89)
    at hellfirepvp.astralsorcery.common.constellation.distribution.ConstellationSkyHandler.tick(ConstellationSkyHandler.java:63)
    at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.worldTick(TickManager.java:55)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_911_TickManager_worldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

```

**Comment by Doomgull** [comment]
What version of AS? There was another set of protections/work arounds for this in 1.9.3.

**Comment by ruifung** [comment]
Huh. AS 1.9.3 was released. I'll close this first until I can test with that. (Was using 1.9.2)
