### ISSUE TITLE
CRASH WITH NEW VERSION

### ISSUE THREAD

**Issue by jsebastianvic** [HellFirePvP/AstralSorcery#931]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.0-core.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 12/11/18 11:43 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at noppes.npcs.items.ItemScripted.getItemStackLimit(ItemScripted.java:62)
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:248)
	at hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted(EnchantmentUpgradeHelper.java:189)
	at hellfirepvp.astralsorcery.common.enchantment.amulet.PlayerAmuletHandler.attachAmuletItemCapability(PlayerAmuletHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_873_PlayerAmuletHandler_attachAmuletItemCapability_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:650)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:95)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:90)
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:201)
	at net.minecraft.stats.StatList.reinit(StatList.java:346)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:245)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 594075200 bytes (566 MB) / 3892314112 bytes (3712 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_D1 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                  | Version                | Source                                            | Signature                                |
	|:------- |:------------------- |:---------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft           | 1.12.2                 | minecraft.jar                                     | None                                     |
	| UCHIJA  | mcp                 | 9.42                   | minecraft.jar                                     | None                                     |
	| UCHIJA  | FML                 | 8.0.99.99              | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAE | forge               | 14.23.5.2768           | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | micdoodlecore       |                        | minecraft.jar                                     | None                                     |
	| UCHIJA  | baubles             | 1.5.2                  | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHIJA  | astralsorcery       | 1.10.3                 | astralsorcery-1.12.2-1.10.3.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJA  | biomesoplenty       | 7.0.1.2419             | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar     | None                                     |
	| UCHIJA  | thaumcraft          | 6.1.BETA26             | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| UCHIJA  | botania             | r1.10-354              | Botania r1.10-354.jar                             | None                                     |
	| UCHIJA  | coralreef           | 2.0                    | CoralReef-2.4-1.12.2.jar                          | None                                     |
	| UCHIJA  | customspawner       | 3.11.4                 | CustomMobSpawner-3.11.4.jar                       | None                                     |
	| UCHIJA  | customnpcs          | 1.12                   | CustomNPCs_1.12.2(20jan18).jar                    | None                                     |
	| UCHIJA  | cyclopscore         | 0.11.11                | CyclopsCore-1.12.2-0.11.11.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA  | ptrmodellib         | 1.0.0                  | Decocraft-2.5.4_1.12.2.jar                        | None                                     |
	| UCHIJA  | props               | 2.5.4                  | Decocraft-2.5.4_1.12.2.jar                        | None                                     |
	| UCHIJA  | dimdoors            | 3.0.9+287              | DimensionalDoors-3.0.9-287.jar                    | None                                     |
	| UCHIJA  | mocreatures         | 12.0.4                 | DrZharks MoCreatures Mod-12.0.4.jar               | None                                     |
	| UCHIJA  | ebwizardry          | 4.1.2                  | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar    | None                                     |
	| UCHIJA  | evilcraft           | 0.10.64                | EvilCraft-1.12.2-0.10.64.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA  | jei                 | 4.14.0.231             | jei_1.12.2-4.14.0.231.jar                         | None                                     |
	| UCHIJA  | forestry            | 5.8.0.264              | forestry_1.12.2-5.8.0.264.jar                     | None                                     |
	| UCHIJA  | evilcraftcompat     | 1.0.0                  | EvilCraft-1.12.2-0.10.64.jar                      | None                                     |
	| UCHIJA  | extrautils2         | 1.0                    | extrautils2-1.12-1.7.6.jar                        | None                                     |
	| UCHIJA  | familiarfauna       | 1.0.11                 | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| UCHIJA  | galacticraftcore    | 4.0.1.174              | GalacticraftCore-1.12.2-4.0.1.174.jar             | None                                     |
	| UCHIJA  | galacticraftplanets | 4.0.1.174              | Galacticraft-Planets-1.12.2-4.0.1.174.jar         | None                                     |
	| UCHIJA  | llibrary            | 1.7.9                  | llibrary-1.7.9-1.12.2.jar                         | None                                     |
	| UCHIJA  | iceandfire          | 1.5.2                  | iceandfire-1.5.2.jar                              | None                                     |
	| UCHIJA  | journeymap          | 1.12.2-5.5.2           | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJA  | radixcore           | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
	| UCHIJA  | mca                 | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                    | None                                     |
	| UCHIJA  | millenaire          | Millénaire 7.1.0       | millenaire-1.12.2-7.1.0.jar                       | None                                     |
	| UCHIJA  | minecolonies        | 1.12.2-0.10.27-RELEASE | minecolonies-1.12.2-0.10.27-RELEASE-universal.jar | None                                     |
	| UCHIJA  | roots               | 0.104                  | roots-2-0.104.jar                                 | None                                     |
	| UCHIJA  | rustic              | 1.0.3                  | rustic-1.0.3.jar                                  | None                                     |
	| UCHIJA  | sereneseasons       | 1.2.13                 | SereneSeasons-1.12.2-1.2.13-universal.jar         | None                                     |
	| UCHIJA  | twilightforest      | 3.8.689                | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| UCHIJA  | thebetweenlands     | 3.4.0                  | TheBetweenlands-3.4.0-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.30.14' Renderer: 'Intel(R) Iris(TM) Plus Graphics 640'

**Comment by jsebastianvic** [comment]
VERSION 1.10....

**Comment by Doomgull** [comment]
That's a custom NPCs error. You're using a massively outdated version of it. This crash was fixed a long while ago by them, and occurs on any version from 1.9 onwards. #762 contains the info.
