### ISSUE TITLE
Error crash on wold load

### ISSUE THREAD

**Issue by SteamDoge9000** [HellFirePvP/AstralSorcery#951]
For some reason my game keeps crashing and i was told to upload it here considering that part of the issue is being caused by astral society

heres a Link to the Log data:
https://gist.github.com/SteamDoge9000/518b837e16f2a2133c7f7276e669917b

crash report

https://paste.dimdev.org/ofuqolizes.mccrash

**Comment by Doomgull** [comment]
Does it happen without redstone plusplus? Used to be incompatible because of crafting table asm of theirs that wasn't super clean.

**Comment by SteamDoge9000** [comment]
let me try

**Comment by TigerWalts** [comment]
Just run into this too, in this case an **IC2 Advanced Miner**  is causing it:
```
java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?
	at hellfirepvp.astralsorcery.common.data.research.ResearchManager.getProgress(ResearchManager.java:86)
	at hellfirepvp.astralsorcery.common.integrations.mods.thaumcraft.perks.key.KeyEnergyShield.on(KeyEnergyShield.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1011_KeyEnergyShield_on_PostProcessVanilla.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at hellfirepvp.astralsorcery.common.event.AttributeEvent.postProcessVanilla(AttributeEvent.java:137)
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111129_g(SourceFile:200)
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111126_e(SourceFile:176)
	at net.minecraft.entity.EntityLivingBase.func_110138_aP(EntityLivingBase.java:1445)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:166)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:157)
	at ic2.core.Ic2Player.<init>(Ic2Player.java:25)
	at ic2.core.Ic2Player.get(Ic2Player.java:18)
	at ic2.core.util.StackUtil.getDrops(StackUtil.java:1177)
	at ic2.core.block.machine.tileentity.TileEntityAdvMiner.canMine(TileEntityAdvMiner.java:206)
	at ic2.core.block.machine.tileentity.TileEntityAdvMiner.work(TileEntityAdvMiner.java:173)
	at ic2.core.block.machine.tileentity.TileEntityAdvMiner.updateEntityServer(TileEntityAdvMiner.java:116)
	at ic2.core.block.TileEntityBlock.func_73660_a(TileEntityBlock.java:326)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

`ResearchManager.getProgress()` is testing for side and then if the player is an instance of `EntityPlayerMP`. However, I suspect some mods are using `EntityPlayer` on the server side. So both checks fail and the exception is thrown.

https://github.com/HellFirePvP/AstralSorcery/blob/3b898a7f3b85b3100ee9c15c1e1ce8a22af90ac6/src/main/java/hellfirepvp/astralsorcery/common/data/research/ResearchManager.java#L79
```java
    @Nonnull
    public static PlayerProgress getProgress(EntityPlayer player, Side side) {
        if(side == Side.CLIENT) {
            return clientProgress;
        } else if(player instanceof EntityPlayerMP) {
            return getProgress((EntityPlayerMP) player);
        } else {
            throw new IllegalStateException("Called getProgress on neither server or client - what are you?");
        }
    }
```

**Comment by Doomgull** [comment]
Any mod using EntityPlayer is not following forge direction, and is at fault. Also, IC2 already fixed this issue in the latest release.
